"""
Shared fixtures and configuration for functional tests.
Generated by TestKraft - AI-powered test generation platform.
"""
import os
import uuid
from datetime import date, timedelta
from decimal import Decimal

import httpx
import pytest


# ── Configuration ─────────────────────────────────────────────────────────────

BASE_URL = os.getenv("BASE_URL", "http://localhost:8000")


# ── Fixtures ──────────────────────────────────────────────────────────────────

@pytest.fixture
def client():
    """HTTP client for making API requests."""
    return httpx.Client(base_url=BASE_URL, timeout=30.0)


@pytest.fixture
def async_client():
    """Async HTTP client for concurrent requests."""
    return httpx.AsyncClient(base_url=BASE_URL, timeout=30.0)


@pytest.fixture
def sample_policyholder_data():
    """Sample data for creating a policyholder."""
    return {
        "first_name": "John",
        "last_name": "Doe",
        "email": f"john.doe.{uuid.uuid4().hex[:8]}@example.com",
        "phone": "+1-555-0100",
        "date_of_birth": "1985-06-15",
        "address": "123 Main St, Springfield, IL 62701",
    }


@pytest.fixture
def sample_policy_data():
    """Sample data for creating a policy."""
    return {
        "policy_type": "AUTO",
        "premium_amount": "1200.00",
        "coverage_amount": "50000.00",
        "start_date": date.today().isoformat(),
        "end_date": (date.today() + timedelta(days=365)).isoformat(),
        "status": "PENDING",
    }


@pytest.fixture
def sample_claim_data():
    """Sample data for filing a claim."""
    return {
        "claim_type": "COLLISION",
        "description": "Vehicle collision on highway during rush hour traffic. Front bumper and headlight damaged.",
        "amount_requested": "5000.00",
        "incident_date": (date.today() - timedelta(days=7)).isoformat(),
    }


@pytest.fixture
def sample_auto_quote_data():
    """Sample data for auto insurance quote."""
    return {
        "driver_age": 30,
        "vehicle_year": 2020,
        "coverage_type": "COMPREHENSIVE",
        "annual_mileage": 12000,
    }


@pytest.fixture
def sample_home_quote_data():
    """Sample data for home insurance quote."""
    return {
        "home_value": "350000.00",
        "location_risk": "MEDIUM",
        "home_age_years": 15,
        "coverage_type": "STANDARD",
    }


@pytest.fixture
def sample_life_quote_data():
    """Sample data for life insurance quote."""
    return {
        "age": 35,
        "health_score": 85,
        "coverage_amount": "500000.00",
        "term_years": 20,
    }


# ── Helper Functions ──────────────────────────────────────────────────────────

def create_test_policyholder(client, data=None):
    """Helper to create a test policyholder and return the ID."""
    if data is None:
        data = {
            "first_name": "Test",
            "last_name": "User",
            "email": f"test.{uuid.uuid4().hex[:8]}@example.com",
            "phone": "+1-555-0199",
            "date_of_birth": "1990-01-01",
            "address": "456 Test St, Test City, TC 12345",
        }
    response = client.post("/api/policyholders", json=data)
    assert response.status_code == 201
    return response.json()


def create_test_policy(client, policyholder_id, data=None):
    """Helper to create a test policy and return the policy object."""
    if data is None:
        data = {
            "policy_type": "AUTO",
            "premium_amount": "1000.00",
            "coverage_amount": "50000.00",
            "start_date": date.today().isoformat(),
            "end_date": (date.today() + timedelta(days=365)).isoformat(),
            "status": "ACTIVE",
        }
    data["policyholder_id"] = policyholder_id
    response = client.post("/api/policies", json=data)
    assert response.status_code == 201
    return response.json()


def create_test_claim(client, policy_id, data=None):
    """Helper to create a test claim and return the claim object."""
    if data is None:
        data = {
            "claim_type": "COLLISION",
            "description": "Test claim description",
            "amount_requested": "3000.00",
            "incident_date": (date.today() - timedelta(days=5)).isoformat(),
        }
    data["policy_id"] = policy_id
    response = client.post("/api/claims", json=data)
    assert response.status_code == 201
    return response.json()
