"""
Shared fixtures and configuration for functional tests.
Generated by TestKraft - AI-powered test generation platform.
"""
import os
from datetime import date, timedelta
from decimal import Decimal
from typing import Dict, Any
import uuid

import httpx
import pytest


# ══════════════════════════════════════════════════════════════════════════════
# Configuration
# ══════════════════════════════════════════════════════════════════════════════

BASE_URL = os.getenv("BASE_URL", "http://localhost:8000")
API_TIMEOUT = 30.0


# ══════════════════════════════════════════════════════════════════════════════
# HTTP Client Fixture
# ══════════════════════════════════════════════════════════════════════════════

@pytest.fixture
async def client():
    """Async HTTP client for API requests."""
    async with httpx.AsyncClient(base_url=BASE_URL, timeout=API_TIMEOUT) as client:
        yield client


# ══════════════════════════════════════════════════════════════════════════════
# Test Data Factories
# ══════════════════════════════════════════════════════════════════════════════

@pytest.fixture
def policyholder_factory():
    """Factory for creating policyholder test data."""
    def _create(
        first_name: str = "John",
        last_name: str = "Doe",
        email: str = None,
        phone: str = "+1-555-0100",
        date_of_birth: date = None,
        address: str = "123 Main St, Anytown, CA 90210"
    ) -> Dict[str, Any]:
        if email is None:
            # Generate unique email to avoid conflicts
            email = f"test.user.{uuid.uuid4().hex[:8]}@example.com"

        if date_of_birth is None:
            date_of_birth = date(1985, 6, 15)

        return {
            "first_name": first_name,
            "last_name": last_name,
            "email": email,
            "phone": phone,
            "date_of_birth": date_of_birth.isoformat(),
            "address": address
        }

    return _create


@pytest.fixture
def policy_factory():
    """Factory for creating policy test data."""
    def _create(
        policyholder_id: str,
        policy_type: str = "AUTO",
        premium_amount: float = 1200.00,
        coverage_amount: float = 100000.00,
        start_date: date = None,
        end_date: date = None,
        status: str = "PENDING"
    ) -> Dict[str, Any]:
        if start_date is None:
            start_date = date.today()

        if end_date is None:
            end_date = start_date + timedelta(days=365)

        return {
            "policyholder_id": policyholder_id,
            "policy_type": policy_type,
            "premium_amount": premium_amount,
            "coverage_amount": coverage_amount,
            "start_date": start_date.isoformat(),
            "end_date": end_date.isoformat(),
            "status": status
        }

    return _create


@pytest.fixture
def claim_factory():
    """Factory for creating claim test data."""
    def _create(
        policy_id: str,
        claim_type: str = "COLLISION",
        description: str = "Vehicle collision on Highway 101",
        amount_requested: float = 5000.00,
        incident_date: date = None
    ) -> Dict[str, Any]:
        if incident_date is None:
            incident_date = date.today() - timedelta(days=7)

        return {
            "policy_id": policy_id,
            "claim_type": claim_type,
            "description": description,
            "amount_requested": amount_requested,
            "incident_date": incident_date.isoformat()
        }

    return _create


# ══════════════════════════════════════════════════════════════════════════════
# Shared Test Data Fixtures (with cleanup)
# ══════════════════════════════════════════════════════════════════════════════

@pytest.fixture
async def test_policyholder(client, policyholder_factory):
    """Create a test policyholder and clean up after test."""
    payload = policyholder_factory()
    response = await client.post("/api/policyholders", json=payload)
    assert response.status_code == 201
    policyholder = response.json()

    yield policyholder

    # Cleanup (soft delete)
    await client.delete(f"/api/policyholders/{policyholder['id']}")


@pytest.fixture
async def test_policy(client, test_policyholder, policy_factory):
    """Create a test policy and return it."""
    payload = policy_factory(policyholder_id=test_policyholder["id"])
    response = await client.post("/api/policies", json=payload)
    assert response.status_code == 201
    policy = response.json()

    yield policy

    # No explicit cleanup needed - cascade or manual cleanup in tests


@pytest.fixture
async def active_policy(client, test_policyholder, policy_factory):
    """Create an ACTIVE policy for testing claims."""
    payload = policy_factory(
        policyholder_id=test_policyholder["id"],
        status="ACTIVE"
    )
    response = await client.post("/api/policies", json=payload)
    assert response.status_code == 201
    policy = response.json()

    # Update status to ACTIVE
    update_response = await client.put(
        f"/api/policies/{policy['id']}",
        json={"status": "ACTIVE"}
    )
    assert update_response.status_code == 200

    yield update_response.json()


@pytest.fixture
async def test_claim(client, active_policy, claim_factory):
    """Create a test claim against an active policy."""
    payload = claim_factory(policy_id=active_policy["id"])
    response = await client.post("/api/claims", json=payload)
    assert response.status_code == 201
    claim = response.json()

    yield claim

    # No explicit cleanup needed
