"""
Functional tests for Policy Management (FR-1).
Generated by TestKraft - AI-powered test generation platform.

User Story:
- As a policyholder, I want to create and manage insurance policies
- As an agent, I want to issue policies and track policy status
- Acceptance criteria: Create, view, update policies with proper validation
"""
import uuid
from datetime import date, timedelta

import pytest

from conftest import create_test_policyholder


class TestPolicyCreation:
    """Test suite for creating policies (FR-1.1)."""

    def test_create_policy_success(self, client, sample_policy_data):
        """Should successfully create a policy with valid data."""
        # Create policyholder first
        policyholder = create_test_policyholder(client)
        sample_policy_data["policyholder_id"] = policyholder["id"]

        response = client.post("/api/policies", json=sample_policy_data)
        assert response.status_code == 201

        data = response.json()
        assert "id" in data
        assert uuid.UUID(data["id"])
        assert data["policy_type"] == sample_policy_data["policy_type"]
        assert data["premium_amount"] == sample_policy_data["premium_amount"]
        assert data["coverage_amount"] == sample_policy_data["coverage_amount"]
        assert data["status"] == sample_policy_data["status"]

    def test_create_policy_auto_generates_policy_number(self, client):
        """Policy creation should auto-generate unique policy number (FR-1.1.3)."""
        policyholder = create_test_policyholder(client)

        policy_data = {
            "policyholder_id": policyholder["id"],
            "policy_type": "AUTO",
            "premium_amount": "1200.00",
            "coverage_amount": "50000.00",
            "start_date": date.today().isoformat(),
            "end_date": (date.today() + timedelta(days=365)).isoformat(),
            "status": "PENDING",
        }

        response = client.post("/api/policies", json=policy_data)
        assert response.status_code == 201

        data = response.json()
        assert "policy_number" in data
        assert data["policy_number"].startswith("AUTO-")
        assert len(data["policy_number"]) > 5

    def test_create_policy_all_types(self, client):
        """Should support all policy types: AUTO, HOME, LIFE, COMMERCIAL (FR-1.1.2)."""
        policyholder = create_test_policyholder(client)
        policy_types = ["AUTO", "HOME", "LIFE", "COMMERCIAL"]

        for policy_type in policy_types:
            policy_data = {
                "policyholder_id": policyholder["id"],
                "policy_type": policy_type,
                "premium_amount": "1000.00",
                "coverage_amount": "100000.00",
                "start_date": date.today().isoformat(),
                "end_date": (date.today() + timedelta(days=365)).isoformat(),
                "status": "PENDING",
            }
            response = client.post("/api/policies", json=policy_data)
            assert response.status_code == 201, f"Failed to create {policy_type} policy"
            assert response.json()["policy_type"] == policy_type

    def test_create_policy_invalid_policyholder(self, client, sample_policy_data):
        """Should reject policy with non-existent policyholder."""
        sample_policy_data["policyholder_id"] = str(uuid.uuid4())
        response = client.post("/api/policies", json=sample_policy_data)
        # Database constraint should fail
        assert response.status_code in [404, 422, 500]

    def test_create_policy_missing_required_fields(self, client):
        """Should reject policy creation with missing required fields."""
        policyholder = create_test_policyholder(client)
        incomplete_data = {
            "policyholder_id": policyholder["id"],
            "policy_type": "AUTO",
            # Missing premium_amount, coverage_amount, dates
        }
        response = client.post("/api/policies", json=incomplete_data)
        assert response.status_code == 422

    def test_create_policy_invalid_date_range(self, client):
        """Should reject policy where end_date is before start_date."""
        policyholder = create_test_policyholder(client)
        invalid_data = {
            "policyholder_id": policyholder["id"],
            "policy_type": "AUTO",
            "premium_amount": "1200.00",
            "coverage_amount": "50000.00",
            "start_date": date.today().isoformat(),
            "end_date": (date.today() - timedelta(days=1)).isoformat(),  # Before start
            "status": "PENDING",
        }
        response = client.post("/api/policies", json=invalid_data)
        # Business logic should validate this
        assert response.status_code in [201, 422]

    def test_create_policy_completes_in_time(self, client):
        """Policy creation should complete in < 3 seconds (FR-1 AC)."""
        import time
        policyholder = create_test_policyholder(client)

        policy_data = {
            "policyholder_id": policyholder["id"],
            "policy_type": "AUTO",
            "premium_amount": "1200.00",
            "coverage_amount": "50000.00",
            "start_date": date.today().isoformat(),
            "end_date": (date.today() + timedelta(days=365)).isoformat(),
            "status": "PENDING",
        }

        start = time.time()
        response = client.post("/api/policies", json=policy_data)
        duration = time.time() - start

        assert response.status_code == 201
        assert duration < 3.0, f"Policy creation took {duration:.2f}s, expected < 3s"


class TestPolicyRetrieval:
    """Test suite for retrieving policies (FR-1.2)."""

    def test_list_policies_success(self, client):
        """Should list all policies with pagination."""
        policyholder = create_test_policyholder(client)

        # Create multiple policies
        for i in range(3):
            policy_data = {
                "policyholder_id": policyholder["id"],
                "policy_type": "AUTO",
                "premium_amount": f"{1000 + i * 100}.00",
                "coverage_amount": "50000.00",
                "start_date": date.today().isoformat(),
                "end_date": (date.today() + timedelta(days=365)).isoformat(),
                "status": "ACTIVE",
            }
            client.post("/api/policies", json=policy_data)

        response = client.get("/api/policies")
        assert response.status_code == 200
        assert isinstance(response.json(), list)
        assert len(response.json()) >= 3

    def test_list_policies_filter_by_status(self, client):
        """Should filter policies by status (FR-1.2.1)."""
        policyholder = create_test_policyholder(client)

        # Create policies with different statuses
        for status in ["ACTIVE", "PENDING", "CANCELLED"]:
            policy_data = {
                "policyholder_id": policyholder["id"],
                "policy_type": "HOME",
                "premium_amount": "1500.00",
                "coverage_amount": "200000.00",
                "start_date": date.today().isoformat(),
                "end_date": (date.today() + timedelta(days=365)).isoformat(),
                "status": status,
            }
            client.post("/api/policies", json=policy_data)

        # Filter by status
        response = client.get("/api/policies?status=ACTIVE")
        assert response.status_code == 200
        policies = response.json()
        # Should only return ACTIVE policies
        if policies:
            assert all(p["status"] == "ACTIVE" for p in policies)

    def test_list_policies_filter_by_type(self, client):
        """Should filter policies by policy type (FR-1.2.1)."""
        policyholder = create_test_policyholder(client)

        # Create different policy types
        for policy_type in ["AUTO", "HOME"]:
            policy_data = {
                "policyholder_id": policyholder["id"],
                "policy_type": policy_type,
                "premium_amount": "1000.00",
                "coverage_amount": "100000.00",
                "start_date": date.today().isoformat(),
                "end_date": (date.today() + timedelta(days=365)).isoformat(),
                "status": "ACTIVE",
            }
            client.post("/api/policies", json=policy_data)

        # Filter by type
        response = client.get("/api/policies?policy_type=AUTO")
        assert response.status_code == 200
        policies = response.json()
        if policies:
            assert all(p["policy_type"] == "AUTO" for p in policies)

    def test_list_policies_filter_by_policyholder(self, client):
        """Should filter policies by policyholder_id (FR-1.2.1)."""
        policyholder1 = create_test_policyholder(client)
        policyholder2 = create_test_policyholder(client)

        # Create policy for policyholder1
        policy_data = {
            "policyholder_id": policyholder1["id"],
            "policy_type": "AUTO",
            "premium_amount": "1000.00",
            "coverage_amount": "50000.00",
            "start_date": date.today().isoformat(),
            "end_date": (date.today() + timedelta(days=365)).isoformat(),
            "status": "ACTIVE",
        }
        client.post("/api/policies", json=policy_data)

        # Filter by policyholder
        response = client.get(f"/api/policies?policyholder_id={policyholder1['id']}")
        assert response.status_code == 200
        policies = response.json()
        assert len(policies) >= 1
        assert all(p["policyholder_id"] == policyholder1["id"] for p in policies)

    def test_get_policy_by_id_success(self, client):
        """Should retrieve policy by ID with details (FR-1.2.3)."""
        policyholder = create_test_policyholder(client)
        policy_data = {
            "policyholder_id": policyholder["id"],
            "policy_type": "LIFE",
            "premium_amount": "2000.00",
            "coverage_amount": "500000.00",
            "start_date": date.today().isoformat(),
            "end_date": (date.today() + timedelta(days=365)).isoformat(),
            "status": "ACTIVE",
        }
        create_response = client.post("/api/policies", json=policy_data)
        policy_id = create_response.json()["id"]

        # Retrieve by ID
        response = client.get(f"/api/policies/{policy_id}")
        assert response.status_code == 200

        data = response.json()
        assert data["id"] == policy_id
        assert data["policy_type"] == "LIFE"

    def test_get_policy_not_found(self, client):
        """Should return 404 for non-existent policy."""
        fake_id = uuid.uuid4()
        response = client.get(f"/api/policies/{fake_id}")
        assert response.status_code == 404
        assert "not found" in response.json()["detail"].lower()


class TestPolicyUpdate:
    """Test suite for updating policies (FR-1.3)."""

    def test_update_policy_premium(self, client):
        """Should update premium amount (FR-1.3.1)."""
        policyholder = create_test_policyholder(client)
        policy_data = {
            "policyholder_id": policyholder["id"],
            "policy_type": "AUTO",
            "premium_amount": "1000.00",
            "coverage_amount": "50000.00",
            "start_date": date.today().isoformat(),
            "end_date": (date.today() + timedelta(days=365)).isoformat(),
            "status": "ACTIVE",
        }
        create_response = client.post("/api/policies", json=policy_data)
        policy_id = create_response.json()["id"]

        # Update premium
        update_data = {"premium_amount": "1500.00"}
        response = client.put(f"/api/policies/{policy_id}", json=update_data)
        assert response.status_code == 200
        assert response.json()["premium_amount"] == "1500.00"

    def test_update_policy_coverage(self, client):
        """Should update coverage amount (FR-1.3.2)."""
        policyholder = create_test_policyholder(client)
        policy_data = {
            "policyholder_id": policyholder["id"],
            "policy_type": "HOME",
            "premium_amount": "1500.00",
            "coverage_amount": "200000.00",
            "start_date": date.today().isoformat(),
            "end_date": (date.today() + timedelta(days=365)).isoformat(),
            "status": "ACTIVE",
        }
        create_response = client.post("/api/policies", json=policy_data)
        policy_id = create_response.json()["id"]

        # Update coverage
        update_data = {"coverage_amount": "250000.00"}
        response = client.put(f"/api/policies/{policy_id}", json=update_data)
        assert response.status_code == 200
        assert response.json()["coverage_amount"] == "250000.00"

    def test_update_policy_status(self, client):
        """Should change policy status (FR-1.3.4)."""
        policyholder = create_test_policyholder(client)
        policy_data = {
            "policyholder_id": policyholder["id"],
            "policy_type": "AUTO",
            "premium_amount": "1000.00",
            "coverage_amount": "50000.00",
            "start_date": date.today().isoformat(),
            "end_date": (date.today() + timedelta(days=365)).isoformat(),
            "status": "PENDING",
        }
        create_response = client.post("/api/policies", json=policy_data)
        policy_id = create_response.json()["id"]

        # Activate policy
        update_data = {"status": "ACTIVE"}
        response = client.put(f"/api/policies/{policy_id}", json=update_data)
        assert response.status_code == 200
        assert response.json()["status"] == "ACTIVE"

    def test_update_policy_extend_end_date(self, client):
        """Should extend policy end date (FR-1.3.3 - renewals)."""
        policyholder = create_test_policyholder(client)
        policy_data = {
            "policyholder_id": policyholder["id"],
            "policy_type": "AUTO",
            "premium_amount": "1000.00",
            "coverage_amount": "50000.00",
            "start_date": date.today().isoformat(),
            "end_date": (date.today() + timedelta(days=365)).isoformat(),
            "status": "ACTIVE",
        }
        create_response = client.post("/api/policies", json=policy_data)
        policy_id = create_response.json()["id"]

        # Extend policy
        new_end_date = (date.today() + timedelta(days=730)).isoformat()
        update_data = {"end_date": new_end_date}
        response = client.put(f"/api/policies/{policy_id}", json=update_data)
        assert response.status_code == 200
        assert response.json()["end_date"] == new_end_date

    def test_update_policy_not_found(self, client):
        """Should return 404 when updating non-existent policy."""
        fake_id = uuid.uuid4()
        update_data = {"premium_amount": "1500.00"}
        response = client.put(f"/api/policies/{fake_id}", json=update_data)
        assert response.status_code == 404


class TestPolicyDocuments:
    """Test suite for policy document associations (FR-1.2.5)."""

    def test_list_policy_documents(self, client):
        """Should list all documents associated with a policy."""
        policyholder = create_test_policyholder(client)
        policy_data = {
            "policyholder_id": policyholder["id"],
            "policy_type": "AUTO",
            "premium_amount": "1000.00",
            "coverage_amount": "50000.00",
            "start_date": date.today().isoformat(),
            "end_date": (date.today() + timedelta(days=365)).isoformat(),
            "status": "ACTIVE",
        }
        create_response = client.post("/api/policies", json=policy_data)
        policy_id = create_response.json()["id"]

        # List documents
        response = client.get(f"/api/policies/{policy_id}/documents")
        assert response.status_code == 200
        assert isinstance(response.json(), list)


class TestPolicyBusinessRules:
    """Test suite for policy business rule validation."""

    def test_policy_status_lifecycle(self, client):
        """Should follow proper status lifecycle: PENDING → ACTIVE → CANCELLED/EXPIRED."""
        policyholder = create_test_policyholder(client)
        policy_data = {
            "policyholder_id": policyholder["id"],
            "policy_type": "AUTO",
            "premium_amount": "1000.00",
            "coverage_amount": "50000.00",
            "start_date": date.today().isoformat(),
            "end_date": (date.today() + timedelta(days=365)).isoformat(),
            "status": "PENDING",
        }
        create_response = client.post("/api/policies", json=policy_data)
        policy_id = create_response.json()["id"]
        assert create_response.json()["status"] == "PENDING"

        # Activate
        response = client.put(f"/api/policies/{policy_id}", json={"status": "ACTIVE"})
        assert response.status_code == 200
        assert response.json()["status"] == "ACTIVE"

        # Cancel
        response = client.put(f"/api/policies/{policy_id}", json={"status": "CANCELLED"})
        assert response.status_code == 200
        assert response.json()["status"] == "CANCELLED"
