"""
Functional tests for Quote Calculator (FR-3).
Generated by TestKraft - AI-powered test generation platform.

User Stories Covered:
- FR-3.1: Quote Generation for Auto, Home, and Life insurance
- FR-3.2: Quote Persistence (not implemented in current API, but tested for format)
- FR-3.3: Quote-to-Policy Conversion (documented for future)
"""
import pytest
from decimal import Decimal


@pytest.mark.asyncio
class TestAutoQuote:
    """Test auto insurance quote generation (FR-3.1)."""

    async def test_auto_quote_success(self, client):
        """
        FR-3.1.1: Generate auto insurance quote with valid data.
        Acceptance Criteria: Quote generation completes in < 2 seconds
        """
        payload = {
            "driver_age": 30,
            "vehicle_year": 2020,
            "coverage_type": "COMPREHENSIVE",
            "annual_mileage": 12000
        }
        response = await client.post("/api/quotes/auto", json=payload)

        assert response.status_code == 200
        data = response.json()
        assert "premium_monthly" in data
        assert "premium_annual" in data
        assert "coverage_details" in data
        assert float(data["premium_monthly"]) > 0
        assert float(data["premium_annual"]) > 0

    async def test_auto_quote_premium_calculation(self, client):
        """
        FR-3.1.3: Calculate base premium from actuarial tables.
        Acceptance Criteria: Quote calculation accuracy validated
        """
        payload = {
            "driver_age": 35,
            "vehicle_year": 2021,
            "coverage_type": "COLLISION",
            "annual_mileage": 10000
        }
        response = await client.post("/api/quotes/auto", json=payload)

        assert response.status_code == 200
        data = response.json()

        # Verify monthly * 12 ≈ annual
        monthly = float(data["premium_monthly"])
        annual = float(data["premium_annual"])
        assert abs(monthly * 12 - annual) < 0.50  # Allow 50 cent rounding difference

    async def test_auto_quote_all_coverage_types(self, client):
        """
        FR-3.1: Test all coverage types: LIABILITY, COLLISION, COMPREHENSIVE.
        """
        coverage_types = ["LIABILITY", "COLLISION", "COMPREHENSIVE"]

        for coverage_type in coverage_types:
            payload = {
                "driver_age": 30,
                "vehicle_year": 2020,
                "coverage_type": coverage_type,
                "annual_mileage": 12000
            }
            response = await client.post("/api/quotes/auto", json=payload)

            assert response.status_code == 200
            data = response.json()
            assert data["coverage_details"]["coverage_type"] == coverage_type

    async def test_auto_quote_young_driver_surcharge(self, client):
        """
        FR-3.1.5: Apply surcharges for high-risk profiles (young driver).
        """
        young_driver_payload = {
            "driver_age": 18,
            "vehicle_year": 2020,
            "coverage_type": "COMPREHENSIVE",
            "annual_mileage": 12000
        }
        mature_driver_payload = {
            "driver_age": 40,
            "vehicle_year": 2020,
            "coverage_type": "COMPREHENSIVE",
            "annual_mileage": 12000
        }

        young_response = await client.post("/api/quotes/auto", json=young_driver_payload)
        mature_response = await client.post("/api/quotes/auto", json=mature_driver_payload)

        assert young_response.status_code == 200
        assert mature_response.status_code == 200

        young_premium = float(young_response.json()["premium_annual"])
        mature_premium = float(mature_response.json()["premium_annual"])

        # Young driver should pay more
        assert young_premium > mature_premium

    async def test_auto_quote_old_vehicle_discount(self, client):
        """
        FR-3.1.4: Apply discounts for lower-risk profiles (older vehicle).
        """
        new_car_payload = {
            "driver_age": 30,
            "vehicle_year": 2024,
            "coverage_type": "COMPREHENSIVE",
            "annual_mileage": 12000
        }
        old_car_payload = {
            "driver_age": 30,
            "vehicle_year": 2000,
            "coverage_type": "COMPREHENSIVE",
            "annual_mileage": 12000
        }

        new_response = await client.post("/api/quotes/auto", json=new_car_payload)
        old_response = await client.post("/api/quotes/auto", json=old_car_payload)

        assert new_response.status_code == 200
        assert old_response.status_code == 200

        new_premium = float(new_response.json()["premium_annual"])
        old_premium = float(old_response.json()["premium_annual"])

        # Older vehicle should be cheaper
        assert old_premium < new_premium

    async def test_auto_quote_high_mileage_surcharge(self, client):
        """
        FR-3.1.5: Higher mileage increases premium.
        """
        low_mileage_payload = {
            "driver_age": 30,
            "vehicle_year": 2020,
            "coverage_type": "COMPREHENSIVE",
            "annual_mileage": 5000
        }
        high_mileage_payload = {
            "driver_age": 30,
            "vehicle_year": 2020,
            "coverage_type": "COMPREHENSIVE",
            "annual_mileage": 25000
        }

        low_response = await client.post("/api/quotes/auto", json=low_mileage_payload)
        high_response = await client.post("/api/quotes/auto", json=high_mileage_payload)

        assert low_response.status_code == 200
        assert high_response.status_code == 200

        low_premium = float(low_response.json()["premium_annual"])
        high_premium = float(high_response.json()["premium_annual"])

        # High mileage should cost more
        assert high_premium > low_premium

    async def test_auto_quote_missing_required_fields(self, client):
        """
        FR-3.1: Cannot generate quote without required fields.
        """
        payload = {
            "driver_age": 30,
            # Missing vehicle_year
        }
        response = await client.post("/api/quotes/auto", json=payload)

        assert response.status_code == 422  # Validation error

    async def test_auto_quote_invalid_age(self, client):
        """
        FR-3.1.2: Validate customer inputs - age must be 16-100.
        """
        payload = {
            "driver_age": 15,  # Too young
            "vehicle_year": 2020,
            "coverage_type": "COMPREHENSIVE",
            "annual_mileage": 12000
        }
        response = await client.post("/api/quotes/auto", json=payload)

        assert response.status_code == 422

    async def test_auto_quote_invalid_vehicle_year(self, client):
        """
        FR-3.1.2: Validate vehicle year (1990-2025).
        """
        payload = {
            "driver_age": 30,
            "vehicle_year": 1980,  # Too old
            "coverage_type": "COMPREHENSIVE",
            "annual_mileage": 12000
        }
        response = await client.post("/api/quotes/auto", json=payload)

        assert response.status_code == 422


@pytest.mark.asyncio
class TestHomeQuote:
    """Test home insurance quote generation (FR-3.1)."""

    async def test_home_quote_success(self, client):
        """
        FR-3.1.1: Generate home insurance quote with valid data.
        """
        payload = {
            "home_value": 300000,
            "location_risk": "MEDIUM",
            "home_age_years": 15,
            "coverage_type": "STANDARD"
        }
        response = await client.post("/api/quotes/home", json=payload)

        assert response.status_code == 200
        data = response.json()
        assert "premium_monthly" in data
        assert "premium_annual" in data
        assert "coverage_details" in data
        assert float(data["premium_monthly"]) > 0
        assert float(data["premium_annual"]) > 0

    async def test_home_quote_all_coverage_types(self, client):
        """
        FR-3.1: Test all coverage types: BASIC, STANDARD, PREMIUM.
        """
        coverage_types = ["BASIC", "STANDARD", "PREMIUM"]

        for coverage_type in coverage_types:
            payload = {
                "home_value": 300000,
                "location_risk": "MEDIUM",
                "home_age_years": 15,
                "coverage_type": coverage_type
            }
            response = await client.post("/api/quotes/home", json=payload)

            assert response.status_code == 200
            data = response.json()
            assert data["coverage_details"]["coverage_type"] == coverage_type

    async def test_home_quote_high_risk_location_surcharge(self, client):
        """
        FR-3.1.5: High-risk location increases premium.
        """
        low_risk_payload = {
            "home_value": 300000,
            "location_risk": "LOW",
            "home_age_years": 15,
            "coverage_type": "STANDARD"
        }
        high_risk_payload = {
            "home_value": 300000,
            "location_risk": "HIGH",
            "home_age_years": 15,
            "coverage_type": "STANDARD"
        }

        low_response = await client.post("/api/quotes/home", json=low_risk_payload)
        high_response = await client.post("/api/quotes/home", json=high_risk_payload)

        assert low_response.status_code == 200
        assert high_response.status_code == 200

        low_premium = float(low_response.json()["premium_annual"])
        high_premium = float(high_response.json()["premium_annual"])

        # High-risk location should cost more
        assert high_premium > low_premium

    async def test_home_quote_older_home_surcharge(self, client):
        """
        FR-3.1.5: Older homes cost more to insure.
        """
        new_home_payload = {
            "home_value": 300000,
            "location_risk": "MEDIUM",
            "home_age_years": 5,
            "coverage_type": "STANDARD"
        }
        old_home_payload = {
            "home_value": 300000,
            "location_risk": "MEDIUM",
            "home_age_years": 50,
            "coverage_type": "STANDARD"
        }

        new_response = await client.post("/api/quotes/home", json=new_home_payload)
        old_response = await client.post("/api/quotes/home", json=old_home_payload)

        assert new_response.status_code == 200
        assert old_response.status_code == 200

        new_premium = float(new_response.json()["premium_annual"])
        old_premium = float(old_response.json()["premium_annual"])

        # Older home should cost more
        assert old_premium > new_premium

    async def test_home_quote_home_value_impact(self, client):
        """
        FR-3.1.3: Premium based on home value.
        """
        low_value_payload = {
            "home_value": 150000,
            "location_risk": "MEDIUM",
            "home_age_years": 15,
            "coverage_type": "STANDARD"
        }
        high_value_payload = {
            "home_value": 500000,
            "location_risk": "MEDIUM",
            "home_age_years": 15,
            "coverage_type": "STANDARD"
        }

        low_response = await client.post("/api/quotes/home", json=low_value_payload)
        high_response = await client.post("/api/quotes/home", json=high_value_payload)

        assert low_response.status_code == 200
        assert high_response.status_code == 200

        low_premium = float(low_response.json()["premium_annual"])
        high_premium = float(high_response.json()["premium_annual"])

        # Higher value home should cost more
        assert high_premium > low_premium

    async def test_home_quote_invalid_home_value(self, client):
        """
        FR-3.1.2: Validate home value (50000-5000000).
        """
        payload = {
            "home_value": 10000,  # Too low
            "location_risk": "MEDIUM",
            "home_age_years": 15,
            "coverage_type": "STANDARD"
        }
        response = await client.post("/api/quotes/home", json=payload)

        assert response.status_code == 422


@pytest.mark.asyncio
class TestLifeQuote:
    """Test life insurance quote generation (FR-3.1)."""

    async def test_life_quote_success(self, client):
        """
        FR-3.1.1: Generate life insurance quote with valid data.
        """
        payload = {
            "age": 35,
            "health_score": 80,
            "coverage_amount": 500000,
            "term_years": 20
        }
        response = await client.post("/api/quotes/life", json=payload)

        assert response.status_code == 200
        data = response.json()
        assert "premium_monthly" in data
        assert "premium_annual" in data
        assert "coverage_details" in data
        assert float(data["premium_monthly"]) > 0
        assert float(data["premium_annual"]) > 0

    async def test_life_quote_age_impact(self, client):
        """
        FR-3.1.5: Age significantly impacts life insurance premium.
        """
        young_payload = {
            "age": 25,
            "health_score": 80,
            "coverage_amount": 500000,
            "term_years": 20
        }
        older_payload = {
            "age": 55,
            "health_score": 80,
            "coverage_amount": 500000,
            "term_years": 20
        }

        young_response = await client.post("/api/quotes/life", json=young_payload)
        older_response = await client.post("/api/quotes/life", json=older_payload)

        assert young_response.status_code == 200
        assert older_response.status_code == 200

        young_premium = float(young_response.json()["premium_annual"])
        older_premium = float(older_response.json()["premium_annual"])

        # Older person should pay significantly more
        assert older_premium > young_premium

    async def test_life_quote_health_score_impact(self, client):
        """
        FR-3.1.4: Better health score = lower premium.
        """
        poor_health_payload = {
            "age": 35,
            "health_score": 40,
            "coverage_amount": 500000,
            "term_years": 20
        }
        excellent_health_payload = {
            "age": 35,
            "health_score": 95,
            "coverage_amount": 500000,
            "term_years": 20
        }

        poor_response = await client.post("/api/quotes/life", json=poor_health_payload)
        excellent_response = await client.post("/api/quotes/life", json=excellent_health_payload)

        assert poor_response.status_code == 200
        assert excellent_response.status_code == 200

        poor_premium = float(poor_response.json()["premium_annual"])
        excellent_premium = float(excellent_response.json()["premium_annual"])

        # Poor health should cost more
        assert poor_premium > excellent_premium

    async def test_life_quote_coverage_amount_impact(self, client):
        """
        FR-3.1.3: Higher coverage = higher premium.
        """
        low_coverage_payload = {
            "age": 35,
            "health_score": 80,
            "coverage_amount": 250000,
            "term_years": 20
        }
        high_coverage_payload = {
            "age": 35,
            "health_score": 80,
            "coverage_amount": 1000000,
            "term_years": 20
        }

        low_response = await client.post("/api/quotes/life", json=low_coverage_payload)
        high_response = await client.post("/api/quotes/life", json=high_coverage_payload)

        assert low_response.status_code == 200
        assert high_response.status_code == 200

        low_premium = float(low_response.json()["premium_annual"])
        high_premium = float(high_response.json()["premium_annual"])

        # Higher coverage should cost more
        assert high_premium > low_premium

    async def test_life_quote_term_impact(self, client):
        """
        FR-3.1.5: Longer term = higher premium.
        """
        short_term_payload = {
            "age": 35,
            "health_score": 80,
            "coverage_amount": 500000,
            "term_years": 10
        }
        long_term_payload = {
            "age": 35,
            "health_score": 80,
            "coverage_amount": 500000,
            "term_years": 30
        }

        short_response = await client.post("/api/quotes/life", json=short_term_payload)
        long_response = await client.post("/api/quotes/life", json=long_term_payload)

        assert short_response.status_code == 200
        assert long_response.status_code == 200

        short_premium = float(short_response.json()["premium_annual"])
        long_premium = float(long_response.json()["premium_annual"])

        # Longer term should cost more
        assert long_premium > short_premium

    async def test_life_quote_invalid_age(self, client):
        """
        FR-3.1.2: Validate age (18-80 for life insurance).
        """
        payload = {
            "age": 85,  # Too old
            "health_score": 80,
            "coverage_amount": 500000,
            "term_years": 20
        }
        response = await client.post("/api/quotes/life", json=payload)

        assert response.status_code == 422

    async def test_life_quote_invalid_health_score(self, client):
        """
        FR-3.1.2: Validate health score (1-100).
        """
        payload = {
            "age": 35,
            "health_score": 105,  # Out of range
            "coverage_amount": 500000,
            "term_years": 20
        }
        response = await client.post("/api/quotes/life", json=payload)

        assert response.status_code == 422


@pytest.mark.asyncio
class TestQuoteResponseFormat:
    """Test quote response format and structure (FR-3.1.6)."""

    async def test_quote_response_includes_coverage_details(self, client):
        """
        FR-3.1.6: Return quote with coverage details.
        """
        payload = {
            "driver_age": 30,
            "vehicle_year": 2020,
            "coverage_type": "COMPREHENSIVE",
            "annual_mileage": 12000
        }
        response = await client.post("/api/quotes/auto", json=payload)

        assert response.status_code == 200
        data = response.json()
        coverage_details = data["coverage_details"]

        # Verify all input parameters are included in coverage_details
        assert coverage_details["driver_age"] == payload["driver_age"]
        assert coverage_details["vehicle_year"] == payload["vehicle_year"]
        assert coverage_details["coverage_type"] == payload["coverage_type"]
        assert coverage_details["annual_mileage"] == payload["annual_mileage"]

    async def test_quote_response_decimal_precision(self, client):
        """
        FR-3.1: Premium amounts rounded to 2 decimal places.
        """
        payload = {
            "driver_age": 30,
            "vehicle_year": 2020,
            "coverage_type": "COMPREHENSIVE",
            "annual_mileage": 12000
        }
        response = await client.post("/api/quotes/auto", json=payload)

        assert response.status_code == 200
        data = response.json()

        # Verify decimal precision
        monthly = data["premium_monthly"]
        annual = data["premium_annual"]

        # Should have at most 2 decimal places
        assert len(str(monthly).split(".")[-1]) <= 2
        assert len(str(annual).split(".")[-1]) <= 2
