"""
End-to-end functional tests for complete user flows.
Generated by TestKraft - AI-powered test generation platform.

User Flows Covered:
- Sarah (Individual Policyholder): Get quote → Purchase → File claim
- Mike (Insurance Agent): Create policyholder → Issue policy
- Emily (Claims Adjuster): Review claim → Approve/Deny
- Policy lifecycle: Create → Activate → Claim → Cancel
"""
import pytest
import uuid
from datetime import date, timedelta


@pytest.mark.asyncio
class TestSarahPolicyholderFlow:
    """
    Test Sarah's user journey (Individual Policyholder persona).
    User Story: Get a quote and purchase insurance quickly (< 10 minutes).
    """

    async def test_complete_quote_to_policy_flow(self, client, policyholder_factory):
        """
        Complete flow: Get quote → Create account → Purchase policy.
        """
        # Step 1: Get auto insurance quote
        quote_payload = {
            "driver_age": 32,
            "vehicle_year": 2021,
            "coverage_type": "COMPREHENSIVE",
            "annual_mileage": 12000
        }
        quote_response = await client.post("/api/quotes/auto", json=quote_payload)
        assert quote_response.status_code == 200
        quote_data = quote_response.json()
        premium_annual = float(quote_data["premium_annual"])

        # Step 2: Create policyholder account
        policyholder_payload = policyholder_factory(
            first_name="Sarah",
            last_name="Customer"
        )
        policyholder_response = await client.post(
            "/api/policyholders",
            json=policyholder_payload
        )
        assert policyholder_response.status_code == 201
        policyholder_id = policyholder_response.json()["id"]

        # Step 3: Purchase policy based on quote
        policy_payload = {
            "policyholder_id": policyholder_id,
            "policy_type": "AUTO",
            "premium_amount": premium_annual,
            "coverage_amount": 100000.00,
            "start_date": date.today().isoformat(),
            "end_date": (date.today() + timedelta(days=365)).isoformat(),
            "status": "PENDING"
        }
        policy_response = await client.post("/api/policies", json=policy_payload)
        assert policy_response.status_code == 201
        policy_data = policy_response.json()

        # Verify policy created with correct details
        assert policy_data["policyholder_id"] == policyholder_id
        assert policy_data["policy_type"] == "AUTO"
        assert float(policy_data["premium_amount"]) == premium_annual
        assert policy_data["status"] == "PENDING"
        assert "policy_number" in policy_data

        # Cleanup
        await client.delete(f"/api/policyholders/{policyholder_id}")

    async def test_complete_claim_filing_flow(self, client, active_policy):
        """
        Complete flow: Have active policy → File claim with photos → Track status.
        """
        # Step 1: File claim against active policy
        claim_payload = {
            "policy_id": active_policy["id"],
            "claim_type": "COLLISION",
            "description": "Rear-end collision at intersection",
            "amount_requested": 4500.00,
            "incident_date": (date.today() - timedelta(days=3)).isoformat()
        }
        claim_response = await client.post("/api/claims", json=claim_payload)
        assert claim_response.status_code == 201
        claim_data = claim_response.json()
        claim_id = claim_data["id"]

        # Step 2: Upload damage photos
        presign_payload = {
            "file_name": "damage_front.jpg",
            "document_type": "DAMAGE_PHOTO",
            "content_type": "image/jpeg",
            "claim_id": claim_id
        }
        presign_response = await client.post("/api/documents/presign", json=presign_payload)
        assert presign_response.status_code == 200
        file_key = presign_response.json()["file_key"]

        # Register uploaded document
        register_payload = {
            "file_key": file_key,
            "file_name": "damage_front.jpg",
            "document_type": "DAMAGE_PHOTO",
            "claim_id": claim_id
        }
        register_response = await client.post("/api/documents", json=register_payload)
        assert register_response.status_code == 201

        # Step 3: Check claim status
        status_response = await client.get(f"/api/claims/{claim_id}")
        assert status_response.status_code == 200
        status_data = status_response.json()
        assert status_data["status"] == "SUBMITTED"
        assert status_data["claim_number"].startswith("CLM-")


@pytest.mark.asyncio
class TestMikeAgentFlow:
    """
    Test Mike's user journey (Insurance Agent persona).
    User Story: Generate quotes quickly and issue policies immediately.
    """

    async def test_agent_create_customer_and_policy(self, client, policyholder_factory):
        """
        Complete flow: Customer calls → Create account → Generate quote → Issue policy.
        """
        # Step 1: Agent creates customer account during call
        customer_payload = policyholder_factory(
            first_name="John",
            last_name="CustomerCall",
            phone="+1-555-1234"
        )
        customer_response = await client.post(
            "/api/policyholders",
            json=customer_payload
        )
        assert customer_response.status_code == 201
        customer_id = customer_response.json()["id"]

        # Step 2: Agent generates quote for customer
        quote_payload = {
            "home_value": 350000,
            "location_risk": "MEDIUM",
            "home_age_years": 20,
            "coverage_type": "STANDARD"
        }
        quote_response = await client.post("/api/quotes/home", json=quote_payload)
        assert quote_response.status_code == 200
        premium_annual = float(quote_response.json()["premium_annual"])

        # Step 3: Customer agrees, agent issues policy immediately
        policy_payload = {
            "policyholder_id": customer_id,
            "policy_type": "HOME",
            "premium_amount": premium_annual,
            "coverage_amount": 350000.00,
            "start_date": date.today().isoformat(),
            "end_date": (date.today() + timedelta(days=365)).isoformat(),
            "status": "PENDING"
        }
        policy_response = await client.post("/api/policies", json=policy_payload)
        assert policy_response.status_code == 201
        policy_data = policy_response.json()

        # Step 4: Agent activates policy (auto-approval for standard risk)
        activate_response = await client.put(
            f"/api/policies/{policy_data['id']}",
            json={"status": "ACTIVE"}
        )
        assert activate_response.status_code == 200
        assert activate_response.json()["status"] == "ACTIVE"

        # Cleanup
        await client.delete(f"/api/policyholders/{customer_id}")

    async def test_agent_manage_multiple_policies(self, client, test_policyholder):
        """
        Complete flow: Agent manages customer with multiple policies (multi-line).
        """
        # Create AUTO policy
        auto_payload = {
            "policyholder_id": test_policyholder["id"],
            "policy_type": "AUTO",
            "premium_amount": 1200.00,
            "coverage_amount": 100000.00,
            "start_date": date.today().isoformat(),
            "end_date": (date.today() + timedelta(days=365)).isoformat(),
            "status": "ACTIVE"
        }
        auto_response = await client.post("/api/policies", json=auto_payload)
        assert auto_response.status_code == 201

        # Create HOME policy
        home_payload = {
            "policyholder_id": test_policyholder["id"],
            "policy_type": "HOME",
            "premium_amount": 1500.00,
            "coverage_amount": 250000.00,
            "start_date": date.today().isoformat(),
            "end_date": (date.today() + timedelta(days=365)).isoformat(),
            "status": "ACTIVE"
        }
        home_response = await client.post("/api/policies", json=home_payload)
        assert home_response.status_code == 201

        # Agent views all policies for customer
        policies_response = await client.get(
            f"/api/policies?policyholder_id={test_policyholder['id']}"
        )
        assert policies_response.status_code == 200
        policies = policies_response.json()
        assert len(policies) >= 2

        # Verify multi-policy discount opportunity
        policy_types = [p["policy_type"] for p in policies]
        assert "AUTO" in policy_types
        assert "HOME" in policy_types


@pytest.mark.asyncio
class TestEmilyAdjusterFlow:
    """
    Test Emily's user journey (Claims Adjuster persona).
    User Story: Review claims efficiently, detect fraud, communicate transparently.
    """

    async def test_adjuster_review_and_approve_claim(self, client, test_claim):
        """
        Complete flow: New claim arrives → Review → Check documents → Approve.
        """
        # Step 1: Adjuster views claim details
        claim_response = await client.get(f"/api/claims/{test_claim['id']}")
        assert claim_response.status_code == 200
        claim_data = claim_response.json()

        # Step 2: Adjuster reviews claim amount vs coverage
        policy_response = await client.get(f"/api/policies/{claim_data['policy_id']}")
        assert policy_response.status_code == 200
        policy_data = policy_response.json()

        coverage = float(policy_data["coverage_amount"])
        requested = float(claim_data["amount_requested"])
        assert requested <= coverage  # Valid claim amount

        # Step 3: Adjuster updates status to UNDER_REVIEW
        review_response = await client.put(
            f"/api/claims/{test_claim['id']}",
            json={"status": "UNDER_REVIEW"}
        )
        assert review_response.status_code == 200

        # Step 4: Adjuster approves claim with full amount
        approve_response = await client.post(
            f"/api/claims/{test_claim['id']}/approve",
            json={
                "amount_approved": requested,
                "notes": "All documentation verified, claim approved"
            }
        )
        assert approve_response.status_code == 200
        approved_data = approve_response.json()
        assert approved_data["status"] == "APPROVED"
        assert float(approved_data["amount_approved"]) == requested

    async def test_adjuster_review_and_reject_claim(self, client, test_claim):
        """
        Complete flow: New claim → Review → Detect issue → Reject with reason.
        """
        # Step 1: Adjuster reviews claim
        claim_response = await client.get(f"/api/claims/{test_claim['id']}")
        assert claim_response.status_code == 200

        # Step 2: Adjuster finds policy exclusion, rejects claim
        reject_response = await client.post(
            f"/api/claims/{test_claim['id']}/reject",
            json={
                "reason": "Damage occurred during excluded activity (racing). "
                         "Not covered under policy terms Section 4.2."
            }
        )
        assert reject_response.status_code == 200
        rejected_data = reject_response.json()
        assert rejected_data["status"] == "REJECTED"

    async def test_adjuster_partial_approval_flow(self, client, test_claim):
        """
        Complete flow: Claim exceeds reasonable amount → Approve partial amount.
        """
        # Adjuster approves 80% of requested amount
        requested = float(test_claim["amount_requested"])
        approved = requested * 0.8

        approve_response = await client.post(
            f"/api/claims/{test_claim['id']}/approve",
            json={
                "amount_approved": approved,
                "notes": "Approved 80% based on repair estimate from our adjuster"
            }
        )
        assert approve_response.status_code == 200
        data = approve_response.json()
        assert float(data["amount_approved"]) == approved
        assert float(data["amount_requested"]) == requested


@pytest.mark.asyncio
class TestPolicyLifecycle:
    """
    Test complete policy lifecycle from creation to cancellation.
    """

    async def test_policy_full_lifecycle(self, client, policyholder_factory):
        """
        Complete lifecycle: Create → Activate → File claim → Cancel.
        """
        # Step 1: Create policyholder
        policyholder_payload = policyholder_factory()
        ph_response = await client.post("/api/policyholders", json=policyholder_payload)
        assert ph_response.status_code == 201
        policyholder_id = ph_response.json()["id"]

        # Step 2: Create policy (PENDING)
        policy_payload = {
            "policyholder_id": policyholder_id,
            "policy_type": "AUTO",
            "premium_amount": 1200.00,
            "coverage_amount": 100000.00,
            "start_date": date.today().isoformat(),
            "end_date": (date.today() + timedelta(days=365)).isoformat(),
            "status": "PENDING"
        }
        policy_response = await client.post("/api/policies", json=policy_payload)
        assert policy_response.status_code == 201
        policy_id = policy_response.json()["id"]

        # Step 3: Activate policy
        activate_response = await client.put(
            f"/api/policies/{policy_id}",
            json={"status": "ACTIVE"}
        )
        assert activate_response.status_code == 200
        assert activate_response.json()["status"] == "ACTIVE"

        # Step 4: File claim against active policy
        claim_payload = {
            "policy_id": policy_id,
            "claim_type": "COLLISION",
            "description": "Minor fender bender",
            "amount_requested": 2500.00,
            "incident_date": date.today().isoformat()
        }
        claim_response = await client.post("/api/claims", json=claim_payload)
        assert claim_response.status_code == 201
        claim_id = claim_response.json()["id"]

        # Step 5: Approve claim
        approve_response = await client.post(
            f"/api/claims/{claim_id}/approve",
            json={"amount_approved": 2500.00}
        )
        assert approve_response.status_code == 200

        # Step 6: Cancel policy
        cancel_response = await client.put(
            f"/api/policies/{policy_id}",
            json={"status": "CANCELLED"}
        )
        assert cancel_response.status_code == 200
        assert cancel_response.json()["status"] == "CANCELLED"

        # Cleanup
        await client.delete(f"/api/policyholders/{policyholder_id}")

    async def test_policy_renewal_scenario(self, client, test_policy):
        """
        Simulate policy renewal: Extend end date, keep same coverage.
        """
        # Original end date
        original_end_date = test_policy["end_date"]

        # Renew policy: extend by another year
        new_end_date = (date.fromisoformat(original_end_date) + timedelta(days=365)).isoformat()

        renewal_response = await client.put(
            f"/api/policies/{test_policy['id']}",
            json={"end_date": new_end_date}
        )
        assert renewal_response.status_code == 200
        renewed_data = renewal_response.json()
        assert renewed_data["end_date"] == new_end_date
        assert renewed_data["policy_number"] == test_policy["policy_number"]  # Same policy


@pytest.mark.asyncio
class TestMultiStepWorkflows:
    """
    Test complex multi-step workflows.
    """

    async def test_claim_with_documents_workflow(self, client, active_policy):
        """
        Complete workflow: File claim → Upload multiple documents → Approve.
        """
        # Step 1: File claim
        claim_payload = {
            "policy_id": active_policy["id"],
            "claim_type": "FIRE",
            "description": "Kitchen fire caused damage to cabinets and appliances",
            "amount_requested": 8500.00,
            "incident_date": (date.today() - timedelta(days=5)).isoformat()
        }
        claim_response = await client.post("/api/claims", json=claim_payload)
        assert claim_response.status_code == 201
        claim_id = claim_response.json()["id"]

        # Step 2: Upload fire department report
        presign1 = await client.post("/api/documents/presign", json={
            "file_name": "fire_report.pdf",
            "document_type": "FIRE_REPORT",
            "content_type": "application/pdf",
            "claim_id": claim_id
        })
        assert presign1.status_code == 200
        await client.post("/api/documents", json={
            "file_key": presign1.json()["file_key"],
            "file_name": "fire_report.pdf",
            "document_type": "FIRE_REPORT",
            "claim_id": claim_id
        })

        # Step 3: Upload damage photos
        presign2 = await client.post("/api/documents/presign", json={
            "file_name": "damage_photo.jpg",
            "document_type": "DAMAGE_PHOTO",
            "content_type": "image/jpeg",
            "claim_id": claim_id
        })
        assert presign2.status_code == 200
        await client.post("/api/documents", json={
            "file_key": presign2.json()["file_key"],
            "file_name": "damage_photo.jpg",
            "document_type": "DAMAGE_PHOTO",
            "claim_id": claim_id
        })

        # Step 4: Upload repair estimate
        presign3 = await client.post("/api/documents/presign", json={
            "file_name": "repair_estimate.pdf",
            "document_type": "REPAIR_INVOICE",
            "content_type": "application/pdf",
            "claim_id": claim_id
        })
        assert presign3.status_code == 200
        await client.post("/api/documents", json={
            "file_key": presign3.json()["file_key"],
            "file_name": "repair_estimate.pdf",
            "document_type": "REPAIR_INVOICE",
            "claim_id": claim_id
        })

        # Step 5: Adjuster reviews and approves
        approve_response = await client.post(
            f"/api/claims/{claim_id}/approve",
            json={"amount_approved": 8500.00}
        )
        assert approve_response.status_code == 200

    async def test_quote_comparison_workflow(self, client):
        """
        Workflow: Compare quotes for different coverage levels.
        """
        # Get basic quote
        basic_response = await client.post("/api/quotes/home", json={
            "home_value": 300000,
            "location_risk": "MEDIUM",
            "home_age_years": 15,
            "coverage_type": "BASIC"
        })
        assert basic_response.status_code == 200
        basic_premium = float(basic_response.json()["premium_annual"])

        # Get standard quote
        standard_response = await client.post("/api/quotes/home", json={
            "home_value": 300000,
            "location_risk": "MEDIUM",
            "home_age_years": 15,
            "coverage_type": "STANDARD"
        })
        assert standard_response.status_code == 200
        standard_premium = float(standard_response.json()["premium_annual"])

        # Get premium quote
        premium_response = await client.post("/api/quotes/home", json={
            "home_value": 300000,
            "location_risk": "MEDIUM",
            "home_age_years": 15,
            "coverage_type": "PREMIUM"
        })
        assert premium_response.status_code == 200
        premium_premium = float(premium_response.json()["premium_annual"])

        # Verify pricing progression
        assert basic_premium < standard_premium < premium_premium


@pytest.mark.asyncio
class TestErrorRecoveryFlows:
    """
    Test error scenarios and recovery workflows.
    """

    async def test_claim_rejected_then_resubmit(self, client, active_policy):
        """
        Workflow: Claim rejected → Customer provides more info → Resubmit.
        """
        # Step 1: File initial claim
        claim_payload = {
            "policy_id": active_policy["id"],
            "claim_type": "THEFT",
            "description": "Vehicle stolen from parking lot",
            "amount_requested": 15000.00,
            "incident_date": (date.today() - timedelta(days=2)).isoformat()
        }
        claim_response = await client.post("/api/claims", json=claim_payload)
        assert claim_response.status_code == 201
        claim_id = claim_response.json()["id"]

        # Step 2: Adjuster rejects due to missing documentation
        reject_response = await client.post(
            f"/api/claims/{claim_id}/reject",
            json={"reason": "Missing police report"}
        )
        assert reject_response.status_code == 200

        # Step 3: Customer files new claim with police report
        new_claim_payload = {
            "policy_id": active_policy["id"],
            "claim_type": "THEFT",
            "description": "Vehicle stolen from parking lot - police report attached",
            "amount_requested": 15000.00,
            "incident_date": (date.today() - timedelta(days=2)).isoformat()
        }
        new_claim_response = await client.post("/api/claims", json=new_claim_payload)
        assert new_claim_response.status_code == 201
        new_claim_id = new_claim_response.json()["id"]

        # Step 4: Upload police report
        presign_response = await client.post("/api/documents/presign", json={
            "file_name": "police_report.pdf",
            "document_type": "POLICE_REPORT",
            "content_type": "application/pdf",
            "claim_id": new_claim_id
        })
        assert presign_response.status_code == 200

        # Step 5: Adjuster approves new claim
        approve_response = await client.post(
            f"/api/claims/{new_claim_id}/approve",
            json={"amount_approved": 15000.00}
        )
        assert approve_response.status_code == 200
