"""
End-to-end functional tests for complete user journeys.
Generated by TestKraft - AI-powered test generation platform.

User Stories:
- Complete policy purchase flow (quote → purchase → policy issuance)
- Complete claims flow (file → review → approve/deny)
- Agent workflow (create customer → issue policy)
- Customer self-service workflow
"""
import uuid
from datetime import date, timedelta
from decimal import Decimal

import pytest


class TestPolicyPurchaseFlow:
    """Test complete policy purchase flow from quote to issuance."""

    def test_auto_insurance_purchase_flow(self, client):
        """
        User Story: Sarah (Individual Policyholder) purchases auto insurance.
        Flow: Get quote → Create account → Purchase policy → Receive confirmation
        """
        # Step 1: Get auto insurance quote
        quote_request = {
            "driver_age": 32,
            "vehicle_year": 2019,
            "coverage_type": "COMPREHENSIVE",
            "annual_mileage": 15000,
        }
        quote_response = client.post("/api/quotes/auto", json=quote_request)
        assert quote_response.status_code == 200
        quote = quote_response.json()
        annual_premium = Decimal(quote["premium_annual"])

        # Step 2: Create policyholder account
        policyholder_data = {
            "first_name": "Sarah",
            "last_name": "Mitchell",
            "email": f"sarah.mitchell.{uuid.uuid4().hex[:8]}@example.com",
            "phone": "+1-555-0150",
            "date_of_birth": "1992-03-15",
            "address": "789 Oak St, Chicago, IL 60601",
        }
        ph_response = client.post("/api/policyholders", json=policyholder_data)
        assert ph_response.status_code == 201
        policyholder = ph_response.json()

        # Step 3: Purchase policy using quote
        policy_data = {
            "policyholder_id": policyholder["id"],
            "policy_type": "AUTO",
            "premium_amount": str(annual_premium),
            "coverage_amount": "50000.00",
            "start_date": date.today().isoformat(),
            "end_date": (date.today() + timedelta(days=365)).isoformat(),
            "status": "ACTIVE",
        }
        policy_response = client.post("/api/policies", json=policy_data)
        assert policy_response.status_code == 201
        policy = policy_response.json()

        # Step 4: Verify policy details
        assert policy["policy_type"] == "AUTO"
        assert policy["status"] == "ACTIVE"
        assert "policy_number" in policy
        assert policy["policy_number"].startswith("AUTO-")

        # Step 5: Verify policyholder can retrieve their policy
        retrieve_response = client.get(f"/api/policies/{policy['id']}")
        assert retrieve_response.status_code == 200
        assert retrieve_response.json()["id"] == policy["id"]

    def test_home_insurance_purchase_flow(self, client):
        """
        User Story: Customer purchases home insurance online.
        Flow: Quote → Create account → Purchase → Verify
        """
        # Step 1: Get home insurance quote
        quote_request = {
            "home_value": "450000.00",
            "location_risk": "LOW",
            "home_age_years": 8,
            "coverage_type": "PREMIUM",
        }
        quote_response = client.post("/api/quotes/home", json=quote_request)
        assert quote_response.status_code == 200
        annual_premium = Decimal(quote_response.json()["premium_annual"])

        # Step 2: Create policyholder
        policyholder_data = {
            "first_name": "Michael",
            "last_name": "Thompson",
            "email": f"michael.thompson.{uuid.uuid4().hex[:8]}@example.com",
            "phone": "+1-555-0175",
            "date_of_birth": "1980-07-22",
            "address": "456 Elm Ave, Portland, OR 97201",
        }
        ph_response = client.post("/api/policyholders", json=policyholder_data)
        assert ph_response.status_code == 201

        # Step 3: Purchase home insurance policy
        policy_data = {
            "policyholder_id": ph_response.json()["id"],
            "policy_type": "HOME",
            "premium_amount": str(annual_premium),
            "coverage_amount": "450000.00",
            "start_date": date.today().isoformat(),
            "end_date": (date.today() + timedelta(days=365)).isoformat(),
            "status": "ACTIVE",
        }
        policy_response = client.post("/api/policies", json=policy_data)
        assert policy_response.status_code == 201
        assert policy_response.json()["policy_type"] == "HOME"


class TestClaimsProcessingFlow:
    """Test complete claims processing flow."""

    def test_file_and_approve_claim_flow(self, client):
        """
        User Story: Sarah files a collision claim and adjuster approves it.
        Flow: File claim → Upload documents → Adjuster reviews → Approve → Track status
        """
        # Setup: Create policyholder and policy
        policyholder_data = {
            "first_name": "Sarah",
            "last_name": "Claims",
            "email": f"sarah.claims.{uuid.uuid4().hex[:8]}@example.com",
            "phone": "+1-555-0200",
            "date_of_birth": "1988-05-10",
            "address": "321 Pine St, Denver, CO 80202",
        }
        ph_response = client.post("/api/policyholders", json=policyholder_data)
        policyholder = ph_response.json()

        policy_data = {
            "policyholder_id": policyholder["id"],
            "policy_type": "AUTO",
            "premium_amount": "1200.00",
            "coverage_amount": "50000.00",
            "start_date": date.today().isoformat(),
            "end_date": (date.today() + timedelta(days=365)).isoformat(),
            "status": "ACTIVE",
        }
        policy_response = client.post("/api/policies", json=policy_data)
        policy = policy_response.json()

        # Step 1: Customer files claim
        claim_data = {
            "policy_id": policy["id"],
            "claim_type": "COLLISION",
            "description": "Rear-ended at stop light. Bumper and trunk damaged. Other driver admitted fault.",
            "amount_requested": "8500.00",
            "incident_date": (date.today() - timedelta(days=2)).isoformat(),
        }
        claim_response = client.post("/api/claims", json=claim_data)
        assert claim_response.status_code == 201
        claim = claim_response.json()
        assert claim["status"] == "SUBMITTED"
        assert "claim_number" in claim

        # Step 2: Customer uploads supporting documents
        presign_request = {
            "file_name": "damage_photo_front.jpg",
            "document_type": "PHOTO",
            "content_type": "image/jpeg",
            "claim_id": claim["id"],
        }
        presign_response = client.post("/api/documents/presign", json=presign_request)
        assert presign_response.status_code == 200
        file_key = presign_response.json()["file_key"]

        # Register document
        register_request = {
            "file_key": file_key,
            "file_name": "damage_photo_front.jpg",
            "document_type": "PHOTO",
            "claim_id": claim["id"],
        }
        doc_response = client.post("/api/documents", json=register_request)
        assert doc_response.status_code == 201

        # Step 3: Adjuster retrieves claim for review
        review_response = client.get(f"/api/claims/{claim['id']}")
        assert review_response.status_code == 200

        # Step 4: Adjuster approves claim
        approval_data = {
            "amount_approved": "7800.00",  # Approved for slightly less after review
            "notes": "Claim approved. Deductible applied.",
        }
        approve_response = client.post(f"/api/claims/{claim['id']}/approve", json=approval_data)
        assert approve_response.status_code == 200
        approved_claim = approve_response.json()
        assert approved_claim["status"] == "APPROVED"
        assert approved_claim["amount_approved"] == "7800.00"

        # Step 5: Customer checks claim status
        status_response = client.get(f"/api/claims/{claim['id']}")
        assert status_response.status_code == 200
        assert status_response.json()["status"] == "APPROVED"

    def test_file_and_reject_claim_flow(self, client):
        """
        User Story: Adjuster rejects fraudulent claim.
        Flow: File claim → Review → Detect fraud → Reject
        """
        # Setup
        policyholder_data = {
            "first_name": "Test",
            "last_name": "Fraud",
            "email": f"test.fraud.{uuid.uuid4().hex[:8]}@example.com",
        }
        ph_response = client.post("/api/policyholders", json=policyholder_data)

        policy_data = {
            "policyholder_id": ph_response.json()["id"],
            "policy_type": "AUTO",
            "premium_amount": "1000.00",
            "coverage_amount": "30000.00",
            "start_date": date.today().isoformat(),
            "end_date": (date.today() + timedelta(days=365)).isoformat(),
            "status": "ACTIVE",
        }
        policy_response = client.post("/api/policies", json=policy_data)

        # File suspicious claim
        claim_data = {
            "policy_id": policy_response.json()["id"],
            "claim_type": "THEFT",
            "description": "Vehicle stolen",
            "amount_requested": "25000.00",
            "incident_date": date.today().isoformat(),
        }
        claim_response = client.post("/api/claims", json=claim_data)
        claim = claim_response.json()

        # Adjuster rejects claim
        rejection_data = {"reason": "Insufficient documentation and inconsistent statements"}
        reject_response = client.post(f"/api/claims/{claim['id']}/reject", json=rejection_data)
        assert reject_response.status_code == 200
        assert reject_response.json()["status"] == "REJECTED"


class TestAgentWorkflow:
    """Test insurance agent workflow."""

    def test_agent_creates_customer_and_issues_policy(self, client):
        """
        User Story: Mike (Insurance Agent) helps customer get insurance.
        Flow: Create customer → Generate quote → Issue policy → Track commission
        """
        # Step 1: Agent creates new customer in system
        customer_data = {
            "first_name": "Jennifer",
            "last_name": "Martinez",
            "email": f"jennifer.martinez.{uuid.uuid4().hex[:8]}@example.com",
            "phone": "+1-555-0225",
            "date_of_birth": "1995-11-30",
            "address": "654 Maple Dr, Austin, TX 78701",
        }
        customer_response = client.post("/api/policyholders", json=customer_data)
        assert customer_response.status_code == 201
        customer = customer_response.json()

        # Step 2: Agent generates quote for customer (during phone call)
        quote_request = {
            "driver_age": 29,
            "vehicle_year": 2021,
            "coverage_type": "COMPREHENSIVE",
            "annual_mileage": 10000,
        }
        quote_response = client.post("/api/quotes/auto", json=quote_request)
        assert quote_response.status_code == 200
        quote = quote_response.json()

        # Step 3: Customer agrees, agent issues policy immediately
        policy_data = {
            "policyholder_id": customer["id"],
            "policy_type": "AUTO",
            "premium_amount": quote["premium_annual"],
            "coverage_amount": "75000.00",
            "start_date": date.today().isoformat(),
            "end_date": (date.today() + timedelta(days=365)).isoformat(),
            "status": "ACTIVE",
        }
        policy_response = client.post("/api/policies", json=policy_data)
        assert policy_response.status_code == 201
        policy = policy_response.json()

        # Step 4: Verify policy is active
        assert policy["status"] == "ACTIVE"
        assert policy["policy_number"] is not None

        # Step 5: Agent can view customer's policies
        customer_policies = client.get(f"/api/policies?policyholder_id={customer['id']}")
        assert customer_policies.status_code == 200
        assert len(customer_policies.json()) >= 1

    def test_agent_multi_policy_customer(self, client):
        """
        User Story: Agent sells multiple policies to same customer (cross-sell).
        Flow: Create customer → Issue auto policy → Issue home policy
        """
        # Create customer
        customer_data = {
            "first_name": "Robert",
            "last_name": "Johnson",
            "email": f"robert.johnson.{uuid.uuid4().hex[:8]}@example.com",
            "phone": "+1-555-0250",
            "date_of_birth": "1978-04-15",
            "address": "987 Cedar Ln, Seattle, WA 98101",
        }
        customer_response = client.post("/api/policyholders", json=customer_data)
        customer = customer_response.json()

        # Issue auto policy
        auto_policy = {
            "policyholder_id": customer["id"],
            "policy_type": "AUTO",
            "premium_amount": "1400.00",
            "coverage_amount": "50000.00",
            "start_date": date.today().isoformat(),
            "end_date": (date.today() + timedelta(days=365)).isoformat(),
            "status": "ACTIVE",
        }
        auto_response = client.post("/api/policies", json=auto_policy)
        assert auto_response.status_code == 201

        # Issue home policy (cross-sell)
        home_policy = {
            "policyholder_id": customer["id"],
            "policy_type": "HOME",
            "premium_amount": "1800.00",
            "coverage_amount": "350000.00",
            "start_date": date.today().isoformat(),
            "end_date": (date.today() + timedelta(days=365)).isoformat(),
            "status": "ACTIVE",
        }
        home_response = client.post("/api/policies", json=home_policy)
        assert home_response.status_code == 201

        # Verify customer has both policies
        policies_response = client.get(f"/api/policies?policyholder_id={customer['id']}")
        policies = policies_response.json()
        assert len(policies) == 2

        policy_types = {p["policy_type"] for p in policies}
        assert "AUTO" in policy_types
        assert "HOME" in policy_types


class TestCustomerSelfServiceFlow:
    """Test customer self-service capabilities."""

    def test_customer_updates_own_information(self, client):
        """
        User Story: Customer updates contact information online.
        Flow: Create account → Update phone → Update address → Verify
        """
        # Create customer account
        customer_data = {
            "first_name": "Amanda",
            "last_name": "Lee",
            "email": f"amanda.lee.{uuid.uuid4().hex[:8]}@example.com",
            "phone": "+1-555-0300",
            "address": "111 First St, Boston, MA 02101",
        }
        create_response = client.post("/api/policyholders", json=customer_data)
        customer = create_response.json()

        # Update phone number
        update_data = {"phone": "+1-555-0999"}
        update_response = client.put(f"/api/policyholders/{customer['id']}", json=update_data)
        assert update_response.status_code == 200
        assert update_response.json()["phone"] == "+1-555-0999"

        # Update address (moved to new location)
        address_update = {"address": "222 Second Ave, Cambridge, MA 02138"}
        address_response = client.put(f"/api/policyholders/{customer['id']}", json=address_update)
        assert address_response.status_code == 200
        assert address_response.json()["address"] == "222 Second Ave, Cambridge, MA 02138"

    def test_customer_views_policy_and_documents(self, client):
        """
        User Story: Customer logs in to view policy details and documents.
        Flow: Create policy → View policy → View documents
        """
        # Setup
        customer_data = {
            "first_name": "David",
            "last_name": "Wilson",
            "email": f"david.wilson.{uuid.uuid4().hex[:8]}@example.com",
        }
        customer = client.post("/api/policyholders", json=customer_data).json()

        policy_data = {
            "policyholder_id": customer["id"],
            "policy_type": "LIFE",
            "premium_amount": "2500.00",
            "coverage_amount": "750000.00",
            "start_date": date.today().isoformat(),
            "end_date": (date.today() + timedelta(days=365)).isoformat(),
            "status": "ACTIVE",
        }
        policy = client.post("/api/policies", json=policy_data).json()

        # Customer views policy details
        view_response = client.get(f"/api/policies/{policy['id']}")
        assert view_response.status_code == 200
        viewed_policy = view_response.json()
        assert viewed_policy["coverage_amount"] == "750000.00"

        # Customer views policy documents
        docs_response = client.get(f"/api/policies/{policy['id']}/documents")
        assert docs_response.status_code == 200


class TestPolicyRenewalFlow:
    """Test policy renewal workflow."""

    def test_policy_renewal_extension(self, client):
        """
        User Story: Customer renews expiring policy.
        Flow: Policy expiring → Generate renewal quote → Accept → Extend policy
        """
        # Create customer and policy
        customer_data = {
            "first_name": "Linda",
            "last_name": "Brown",
            "email": f"linda.brown.{uuid.uuid4().hex[:8]}@example.com",
        }
        customer = client.post("/api/policyholders", json=customer_data).json()

        # Policy expiring in 30 days
        policy_data = {
            "policyholder_id": customer["id"],
            "policy_type": "AUTO",
            "premium_amount": "1100.00",
            "coverage_amount": "50000.00",
            "start_date": (date.today() - timedelta(days=335)).isoformat(),
            "end_date": (date.today() + timedelta(days=30)).isoformat(),
            "status": "ACTIVE",
        }
        policy = client.post("/api/policies", json=policy_data).json()

        # Generate renewal quote
        quote_request = {
            "driver_age": 45,
            "vehicle_year": 2020,
            "coverage_type": "COMPREHENSIVE",
            "annual_mileage": 12000,
        }
        quote = client.post("/api/quotes/auto", json=quote_request).json()

        # Customer accepts renewal - extend policy
        renewal_data = {
            "end_date": (date.today() + timedelta(days=395)).isoformat(),  # Extend 1 year
            "premium_amount": quote["premium_annual"],
        }
        renew_response = client.put(f"/api/policies/{policy['id']}", json=renewal_data)
        assert renew_response.status_code == 200
        renewed_policy = renew_response.json()
        assert renewed_policy["end_date"] == renewal_data["end_date"]


class TestPerformanceRequirements:
    """Test that system meets performance requirements from NFR-1."""

    def test_quote_to_policy_within_target_time(self, client):
        """
        Business Goal: Policy issuance in < 1 hour (target from BRD).
        Test: Complete flow should be fast (quote + create account + issue policy < 10 seconds).
        """
        import time

        start = time.time()

        # Get quote
        quote_response = client.post("/api/quotes/auto", json={
            "driver_age": 35,
            "vehicle_year": 2021,
            "coverage_type": "COMPREHENSIVE",
            "annual_mileage": 12000,
        })
        quote = quote_response.json()

        # Create account
        customer_data = {
            "first_name": "Speed",
            "last_name": "Test",
            "email": f"speed.test.{uuid.uuid4().hex[:8]}@example.com",
        }
        customer = client.post("/api/policyholders", json=customer_data).json()

        # Issue policy
        policy_data = {
            "policyholder_id": customer["id"],
            "policy_type": "AUTO",
            "premium_amount": quote["premium_annual"],
            "coverage_amount": "50000.00",
            "start_date": date.today().isoformat(),
            "end_date": (date.today() + timedelta(days=365)).isoformat(),
            "status": "ACTIVE",
        }
        policy = client.post("/api/policies", json=policy_data).json()

        duration = time.time() - start

        assert policy["status"] == "ACTIVE"
        assert duration < 10.0, f"Flow took {duration:.2f}s, expected < 10s"
