"""
Functional tests for Document Management (FR-4).
Generated by TestKraft - AI-powered test generation platform.

User Stories Covered:
- FR-4.1: Document Upload (presigned URL flow)
- FR-4.2: Document Retrieval (presigned download URL)
- FR-4.3: Document Types (policy, claim, customer documents)
"""
import pytest
import uuid


@pytest.mark.asyncio
class TestDocumentPresignedUpload:
    """Test document presigned URL generation for upload (FR-4.1)."""

    async def test_get_presigned_upload_url_for_claim(self, client, test_claim):
        """
        FR-4.1.1: Generate presigned URL for claim document upload.
        """
        payload = {
            "file_name": "accident_photo.jpg",
            "document_type": "ACCIDENT_PHOTO",
            "content_type": "image/jpeg",
            "claim_id": test_claim["id"]
        }
        response = await client.post("/api/documents/presign", json=payload)

        assert response.status_code == 200
        data = response.json()
        assert "upload_url" in data
        assert "file_key" in data
        assert isinstance(data["upload_url"], str)
        assert len(data["upload_url"]) > 0
        assert isinstance(data["file_key"], str)

    async def test_get_presigned_upload_url_for_policy(self, client, test_policy):
        """
        FR-4.1.1: Generate presigned URL for policy document upload.
        """
        payload = {
            "file_name": "policy_terms.pdf",
            "document_type": "POLICY_TERMS",
            "content_type": "application/pdf",
            "policy_id": test_policy["id"]
        }
        response = await client.post("/api/documents/presign", json=payload)

        assert response.status_code == 200
        data = response.json()
        assert "upload_url" in data
        assert "file_key" in data

    async def test_get_presigned_upload_url_without_association(self, client):
        """
        FR-4.1.1: Generate presigned URL without claim/policy association.
        """
        payload = {
            "file_name": "customer_id.jpg",
            "document_type": "CUSTOMER_ID",
            "content_type": "image/jpeg"
        }
        response = await client.post("/api/documents/presign", json=payload)

        assert response.status_code == 200
        data = response.json()
        assert "upload_url" in data
        assert "file_key" in data

    async def test_get_presigned_upload_url_pdf(self, client, test_claim):
        """
        FR-4.1.2: Support PDF document type.
        """
        payload = {
            "file_name": "police_report.pdf",
            "document_type": "POLICE_REPORT",
            "content_type": "application/pdf",
            "claim_id": test_claim["id"]
        }
        response = await client.post("/api/documents/presign", json=payload)

        assert response.status_code == 200

    async def test_get_presigned_upload_url_missing_required_fields(self, client):
        """
        FR-4.1: Cannot generate presigned URL without required fields.
        """
        payload = {
            "file_name": "test.jpg",
            # Missing document_type and content_type
        }
        response = await client.post("/api/documents/presign", json=payload)

        assert response.status_code == 422  # Validation error


@pytest.mark.asyncio
class TestDocumentRegistration:
    """Test document registration after upload (FR-4.1.5)."""

    async def test_register_document_for_claim(self, client, test_claim):
        """
        FR-4.1.5: Register document metadata after S3 upload.
        """
        # First get presigned URL
        presign_payload = {
            "file_name": "damage_photo.jpg",
            "document_type": "DAMAGE_PHOTO",
            "content_type": "image/jpeg",
            "claim_id": test_claim["id"]
        }
        presign_response = await client.post("/api/documents/presign", json=presign_payload)
        assert presign_response.status_code == 200
        file_key = presign_response.json()["file_key"]

        # Register document
        register_payload = {
            "file_key": file_key,
            "file_name": "damage_photo.jpg",
            "document_type": "DAMAGE_PHOTO",
            "claim_id": test_claim["id"]
        }
        response = await client.post("/api/documents", json=register_payload)

        assert response.status_code == 201
        data = response.json()
        assert "id" in data
        assert uuid.UUID(data["id"])  # Valid UUID
        assert data["file_name"] == register_payload["file_name"]
        assert data["document_type"] == register_payload["document_type"]
        assert data["claim_id"] == test_claim["id"]

    async def test_register_document_for_policy(self, client, test_policy):
        """
        FR-4.1.5: Register document for policy.
        """
        # Get presigned URL
        presign_payload = {
            "file_name": "policy_certificate.pdf",
            "document_type": "POLICY_CERTIFICATE",
            "content_type": "application/pdf",
            "policy_id": test_policy["id"]
        }
        presign_response = await client.post("/api/documents/presign", json=presign_payload)
        assert presign_response.status_code == 200
        file_key = presign_response.json()["file_key"]

        # Register document
        register_payload = {
            "file_key": file_key,
            "file_name": "policy_certificate.pdf",
            "document_type": "POLICY_CERTIFICATE",
            "policy_id": test_policy["id"]
        }
        response = await client.post("/api/documents", json=register_payload)

        assert response.status_code == 201
        data = response.json()
        assert data["policy_id"] == test_policy["id"]
        assert data["claim_id"] is None

    async def test_register_document_without_association(self, client):
        """
        FR-4.1.5: Register document without claim/policy association.
        """
        register_payload = {
            "file_key": "test-key-12345",
            "file_name": "customer_document.pdf",
            "document_type": "CUSTOMER_ID"
        }
        response = await client.post("/api/documents", json=register_payload)

        assert response.status_code == 201
        data = response.json()
        assert data["claim_id"] is None
        assert data["policy_id"] is None

    async def test_register_document_missing_required_fields(self, client):
        """
        FR-4.1.5: Cannot register document without required fields.
        """
        payload = {
            "file_name": "test.pdf",
            # Missing file_key and document_type
        }
        response = await client.post("/api/documents", json=payload)

        assert response.status_code == 422


@pytest.mark.asyncio
class TestDocumentRetrieval:
    """Test document download URL generation (FR-4.2)."""

    async def test_get_document_download_url(self, client, test_claim):
        """
        FR-4.2.2: Generate presigned download URL for document.
        Acceptance Criteria: Presigned URLs expire after 15 minutes
        """
        # First register a document
        register_payload = {
            "file_key": "test-claim-doc-123",
            "file_name": "test_document.pdf",
            "document_type": "TEST_DOC",
            "claim_id": test_claim["id"]
        }
        register_response = await client.post("/api/documents", json=register_payload)
        assert register_response.status_code == 201
        document_id = register_response.json()["id"]

        # Get download URL
        response = await client.get(f"/api/documents/{document_id}")

        assert response.status_code == 200
        data = response.json()
        assert "download_url" in data
        assert "file_name" in data
        assert isinstance(data["download_url"], str)
        assert len(data["download_url"]) > 0
        assert data["file_name"] == "test_document.pdf"

    async def test_get_document_download_url_not_found(self, client):
        """
        FR-4.2.2: Get download URL for non-existent document returns 404.
        """
        fake_id = str(uuid.uuid4())
        response = await client.get(f"/api/documents/{fake_id}")

        assert response.status_code == 404
        assert "not found" in response.json()["detail"].lower()

    async def test_get_document_download_url_invalid_uuid(self, client):
        """
        FR-4.2.2: Invalid document ID returns 422.
        """
        response = await client.get("/api/documents/invalid-uuid")

        assert response.status_code == 422


@pytest.mark.asyncio
class TestDocumentTypes:
    """Test different document types (FR-4.3)."""

    async def test_policy_document_types(self, client, test_policy):
        """
        FR-4.3.1: Policy Documents: Terms, Endorsements, Certificates.
        """
        policy_doc_types = [
            "POLICY_TERMS",
            "POLICY_ENDORSEMENT",
            "POLICY_CERTIFICATE",
            "POLICY_DECLARATION"
        ]

        for doc_type in policy_doc_types:
            # Get presigned URL
            presign_payload = {
                "file_name": f"{doc_type.lower()}.pdf",
                "document_type": doc_type,
                "content_type": "application/pdf",
                "policy_id": test_policy["id"]
            }
            presign_response = await client.post("/api/documents/presign", json=presign_payload)
            assert presign_response.status_code == 200
            file_key = presign_response.json()["file_key"]

            # Register document
            register_payload = {
                "file_key": file_key,
                "file_name": f"{doc_type.lower()}.pdf",
                "document_type": doc_type,
                "policy_id": test_policy["id"]
            }
            register_response = await client.post("/api/documents", json=register_payload)
            assert register_response.status_code == 201
            assert register_response.json()["document_type"] == doc_type

    async def test_claim_document_types(self, client, test_claim):
        """
        FR-4.3.2: Claim Documents: Photos, Police Reports, Invoices, Medical Records.
        """
        claim_doc_types = [
            "ACCIDENT_PHOTO",
            "DAMAGE_PHOTO",
            "POLICE_REPORT",
            "REPAIR_INVOICE",
            "MEDICAL_RECORD",
            "WITNESS_STATEMENT"
        ]

        for doc_type in claim_doc_types:
            # Get presigned URL
            presign_payload = {
                "file_name": f"{doc_type.lower()}.pdf",
                "document_type": doc_type,
                "content_type": "application/pdf",
                "claim_id": test_claim["id"]
            }
            presign_response = await client.post("/api/documents/presign", json=presign_payload)
            assert presign_response.status_code == 200
            file_key = presign_response.json()["file_key"]

            # Register document
            register_payload = {
                "file_key": file_key,
                "file_name": f"{doc_type.lower()}.pdf",
                "document_type": doc_type,
                "claim_id": test_claim["id"]
            }
            register_response = await client.post("/api/documents", json=register_payload)
            assert register_response.status_code == 201
            assert register_response.json()["document_type"] == doc_type

    async def test_customer_document_types(self, client):
        """
        FR-4.3.3: Customer Documents: ID, Proof of Residence, Inspection Reports.
        """
        customer_doc_types = [
            "CUSTOMER_ID",
            "PROOF_OF_RESIDENCE",
            "INSPECTION_REPORT",
            "DRIVER_LICENSE"
        ]

        for doc_type in customer_doc_types:
            # Get presigned URL
            presign_payload = {
                "file_name": f"{doc_type.lower()}.pdf",
                "document_type": doc_type,
                "content_type": "application/pdf"
            }
            presign_response = await client.post("/api/documents/presign", json=presign_payload)
            assert presign_response.status_code == 200
            file_key = presign_response.json()["file_key"]

            # Register document
            register_payload = {
                "file_key": file_key,
                "file_name": f"{doc_type.lower()}.pdf",
                "document_type": doc_type
            }
            register_response = await client.post("/api/documents", json=register_payload)
            assert register_response.status_code == 201
            assert register_response.json()["document_type"] == doc_type


@pytest.mark.asyncio
class TestDocumentListingForResources:
    """Test listing documents for policies and claims (FR-4.2.1)."""

    async def test_list_policy_documents(self, client, test_policy):
        """
        FR-4.2.1: List all documents for a policy.
        """
        # Create a document for the policy
        register_payload = {
            "file_key": f"policy-doc-{uuid.uuid4().hex[:8]}",
            "file_name": "policy_document.pdf",
            "document_type": "POLICY_TERMS",
            "policy_id": test_policy["id"]
        }
        await client.post("/api/documents", json=register_payload)

        # List policy documents
        response = await client.get(f"/api/policies/{test_policy['id']}/documents")

        assert response.status_code == 200
        data = response.json()
        assert isinstance(data, list)
        # Should have at least the document we created
        # (may have more if other tests created documents)

    async def test_list_claim_documents_via_claim_detail(self, client, test_claim):
        """
        FR-4.2.1: View uploaded documents for a claim.
        """
        # Create a document for the claim
        register_payload = {
            "file_key": f"claim-doc-{uuid.uuid4().hex[:8]}",
            "file_name": "claim_evidence.jpg",
            "document_type": "ACCIDENT_PHOTO",
            "claim_id": test_claim["id"]
        }
        await client.post("/api/documents", json=register_payload)

        # Get claim (should include document reference)
        response = await client.get(f"/api/claims/{test_claim['id']}")

        assert response.status_code == 200
        # Claim detail loaded successfully


@pytest.mark.asyncio
class TestDocumentSecurity:
    """Test document security (FR-4, NFR-4)."""

    async def test_presigned_url_contains_signature(self, client, test_claim):
        """
        FR-4.2.3: Presigned URLs should contain signature/token.
        """
        payload = {
            "file_name": "secure_doc.pdf",
            "document_type": "CLAIM_DOC",
            "content_type": "application/pdf",
            "claim_id": test_claim["id"]
        }
        response = await client.post("/api/documents/presign", json=payload)

        assert response.status_code == 200
        upload_url = response.json()["upload_url"]

        # Presigned URL should be an HTTPS URL
        assert upload_url.startswith("http")

        # Note: In real implementation, this should be HTTPS
        # and contain AWS signature parameters

    async def test_document_audit_trail(self, client, test_claim):
        """
        FR-4.2.4: Document access should be auditable.
        (This test documents the requirement; actual audit logging
        may be implemented in application logs or CloudTrail)
        """
        # Register document
        register_payload = {
            "file_key": "audit-test-doc",
            "file_name": "audit_test.pdf",
            "document_type": "TEST_DOC",
            "claim_id": test_claim["id"]
        }
        register_response = await client.post("/api/documents", json=register_payload)
        assert register_response.status_code == 201
        document_id = register_response.json()["id"]

        # Access document (generate download URL)
        download_response = await client.get(f"/api/documents/{document_id}")
        assert download_response.status_code == 200

        # Audit trail should be logged (verified via application logs)
        # This test documents the requirement
