"""
Functional tests for health check endpoint.
Generated by TestKraft - AI-powered test generation platform.
"""
import pytest


class TestHealthCheck:
    """Test suite for health check endpoint."""

    def test_health_check_returns_200(self, client):
        """Health check should return 200 OK."""
        response = client.get("/health")
        assert response.status_code == 200

    def test_health_check_response_structure(self, client):
        """Health check should return expected JSON structure."""
        response = client.get("/health")
        data = response.json()

        assert "status" in data
        assert "service" in data
        assert "version" in data

    def test_health_check_status_healthy(self, client):
        """Health check should report healthy status."""
        response = client.get("/health")
        data = response.json()

        assert data["status"] == "healthy"
        assert data["service"] == "InsureCo Insurance Portal API"
        assert data["version"] == "1.0.0"

    def test_health_check_no_authentication_required(self, client):
        """Health check should not require authentication."""
        # No auth headers needed
        response = client.get("/health")
        assert response.status_code == 200
