"""
Functional tests for Document Management (FR-4).
Generated by TestKraft - AI-powered test generation platform.

User Story:
- As a policyholder, I want to upload claim documents (photos, receipts)
- As an adjuster, I want to securely access claim documents
- Acceptance criteria: Upload documents, generate presigned URLs, secure storage
"""
import uuid

import pytest

from conftest import create_test_policyholder, create_test_policy, create_test_claim


class TestDocumentPresignedUrls:
    """Test suite for generating presigned upload URLs (FR-4.1)."""

    def test_get_presigned_url_for_claim_document(self, client):
        """Should generate presigned URL for claim document upload."""
        policyholder = create_test_policyholder(client)
        policy = create_test_policy(client, policyholder["id"])
        claim = create_test_claim(client, policy["id"])

        presign_request = {
            "file_name": "accident_photo.jpg",
            "document_type": "PHOTO",
            "content_type": "image/jpeg",
            "claim_id": claim["id"],
        }

        response = client.post("/api/documents/presign", json=presign_request)
        assert response.status_code == 200

        data = response.json()
        assert "upload_url" in data
        assert "file_key" in data
        assert len(data["upload_url"]) > 0
        assert len(data["file_key"]) > 0

    def test_get_presigned_url_for_policy_document(self, client):
        """Should generate presigned URL for policy document upload."""
        policyholder = create_test_policyholder(client)
        policy = create_test_policy(client, policyholder["id"])

        presign_request = {
            "file_name": "policy_terms.pdf",
            "document_type": "TERMS",
            "content_type": "application/pdf",
            "policy_id": policy["id"],
        }

        response = client.post("/api/documents/presign", json=presign_request)
        assert response.status_code == 200

        data = response.json()
        assert "upload_url" in data
        assert "file_key" in data

    def test_get_presigned_url_supported_file_types(self, client):
        """Should support common document file types (FR-4.1.2)."""
        policyholder = create_test_policyholder(client)
        policy = create_test_policy(client, policyholder["id"])

        file_types = [
            ("document.pdf", "application/pdf"),
            ("photo.jpg", "image/jpeg"),
            ("photo.png", "image/png"),
            ("report.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"),
        ]

        for file_name, content_type in file_types:
            presign_request = {
                "file_name": file_name,
                "document_type": "GENERAL",
                "content_type": content_type,
                "policy_id": policy["id"],
            }
            response = client.post("/api/documents/presign", json=presign_request)
            assert response.status_code == 200, f"Failed for {file_name}"

    def test_get_presigned_url_missing_required_fields(self, client):
        """Should reject request with missing required fields."""
        incomplete_request = {
            "file_name": "test.jpg",
            # Missing document_type and content_type
        }
        response = client.post("/api/documents/presign", json=incomplete_request)
        assert response.status_code == 422

    def test_presigned_url_generation_fast(self, client):
        """Presigned URL generation should be fast (< 1 second)."""
        import time
        policyholder = create_test_policyholder(client)
        policy = create_test_policy(client, policyholder["id"])

        presign_request = {
            "file_name": "test.jpg",
            "document_type": "PHOTO",
            "content_type": "image/jpeg",
            "policy_id": policy["id"],
        }

        start = time.time()
        response = client.post("/api/documents/presign", json=presign_request)
        duration = time.time() - start

        assert response.status_code == 200
        assert duration < 1.0, f"Presigned URL took {duration:.2f}s"


class TestDocumentRegistration:
    """Test suite for registering uploaded documents (FR-4.1.5)."""

    def test_register_document_for_claim(self, client):
        """Should register document after upload to S3."""
        policyholder = create_test_policyholder(client)
        policy = create_test_policy(client, policyholder["id"])
        claim = create_test_claim(client, policy["id"])

        # First get presigned URL
        presign_request = {
            "file_name": "accident_scene.jpg",
            "document_type": "PHOTO",
            "content_type": "image/jpeg",
            "claim_id": claim["id"],
        }
        presign_response = client.post("/api/documents/presign", json=presign_request)
        file_key = presign_response.json()["file_key"]

        # Register document
        register_request = {
            "file_key": file_key,
            "file_name": "accident_scene.jpg",
            "document_type": "PHOTO",
            "claim_id": claim["id"],
        }
        response = client.post("/api/documents", json=register_request)
        assert response.status_code == 201

        data = response.json()
        assert "id" in data
        assert uuid.UUID(data["id"])
        assert data["file_name"] == "accident_scene.jpg"
        assert data["document_type"] == "PHOTO"
        assert data["claim_id"] == claim["id"]

    def test_register_document_for_policy(self, client):
        """Should register document associated with policy."""
        policyholder = create_test_policyholder(client)
        policy = create_test_policy(client, policyholder["id"])

        presign_request = {
            "file_name": "policy_cert.pdf",
            "document_type": "CERTIFICATE",
            "content_type": "application/pdf",
            "policy_id": policy["id"],
        }
        presign_response = client.post("/api/documents/presign", json=presign_request)
        file_key = presign_response.json()["file_key"]

        register_request = {
            "file_key": file_key,
            "file_name": "policy_cert.pdf",
            "document_type": "CERTIFICATE",
            "policy_id": policy["id"],
        }
        response = client.post("/api/documents", json=register_request)
        assert response.status_code == 201
        assert response.json()["policy_id"] == policy["id"]

    def test_register_document_missing_required_fields(self, client):
        """Should reject registration with missing fields."""
        incomplete_request = {
            "file_key": "test-key",
            # Missing file_name and document_type
        }
        response = client.post("/api/documents", json=incomplete_request)
        assert response.status_code == 422

    def test_register_document_stores_metadata(self, client):
        """Should store document metadata in database (FR-4.1.5)."""
        policyholder = create_test_policyholder(client)
        policy = create_test_policy(client, policyholder["id"])

        presign_request = {
            "file_name": "inspection_report.pdf",
            "document_type": "INSPECTION",
            "content_type": "application/pdf",
            "policy_id": policy["id"],
        }
        presign_response = client.post("/api/documents/presign", json=presign_request)
        file_key = presign_response.json()["file_key"]

        register_request = {
            "file_key": file_key,
            "file_name": "inspection_report.pdf",
            "document_type": "INSPECTION",
            "policy_id": policy["id"],
        }
        response = client.post("/api/documents", json=register_request)
        data = response.json()

        # Metadata should be present
        assert data["file_name"] == "inspection_report.pdf"
        assert data["document_type"] == "INSPECTION"
        assert "id" in data


class TestDocumentRetrieval:
    """Test suite for retrieving documents (FR-4.2)."""

    def test_get_document_download_url(self, client):
        """Should generate presigned download URL for document (FR-4.2.2)."""
        policyholder = create_test_policyholder(client)
        policy = create_test_policy(client, policyholder["id"])

        # Create and register document
        presign_request = {
            "file_name": "test_doc.pdf",
            "document_type": "TEST",
            "content_type": "application/pdf",
            "policy_id": policy["id"],
        }
        presign_response = client.post("/api/documents/presign", json=presign_request)
        file_key = presign_response.json()["file_key"]

        register_request = {
            "file_key": file_key,
            "file_name": "test_doc.pdf",
            "document_type": "TEST",
            "policy_id": policy["id"],
        }
        register_response = client.post("/api/documents", json=register_request)
        document_id = register_response.json()["id"]

        # Get download URL
        response = client.get(f"/api/documents/{document_id}")
        assert response.status_code == 200

        data = response.json()
        assert "download_url" in data
        assert "file_name" in data
        assert len(data["download_url"]) > 0
        assert data["file_name"] == "test_doc.pdf"

    def test_get_document_not_found(self, client):
        """Should return 404 for non-existent document."""
        fake_id = uuid.uuid4()
        response = client.get(f"/api/documents/{fake_id}")
        assert response.status_code == 404
        assert "not found" in response.json()["detail"].lower()

    def test_get_document_download_url_expires(self, client):
        """Download URL should have expiration (FR-4.2.3)."""
        policyholder = create_test_policyholder(client)
        policy = create_test_policy(client, policyholder["id"])

        presign_request = {
            "file_name": "expiry_test.pdf",
            "document_type": "TEST",
            "content_type": "application/pdf",
            "policy_id": policy["id"],
        }
        presign_response = client.post("/api/documents/presign", json=presign_request)
        file_key = presign_response.json()["file_key"]

        register_request = {
            "file_key": file_key,
            "file_name": "expiry_test.pdf",
            "document_type": "TEST",
            "policy_id": policy["id"],
        }
        register_response = client.post("/api/documents", json=register_request)
        document_id = register_response.json()["id"]

        response = client.get(f"/api/documents/{document_id}")
        data = response.json()

        # URL should contain expiration parameters (S3 presigned URL format)
        download_url = data["download_url"]
        assert "Expires" in download_url or "X-Amz-Expires" in download_url


class TestDocumentTypes:
    """Test suite for different document types (FR-4.3)."""

    def test_policy_document_types(self, client):
        """Should support policy document types (FR-4.3.1)."""
        policyholder = create_test_policyholder(client)
        policy = create_test_policy(client, policyholder["id"])

        policy_doc_types = ["TERMS", "ENDORSEMENT", "CERTIFICATE"]

        for doc_type in policy_doc_types:
            presign_request = {
                "file_name": f"{doc_type.lower()}.pdf",
                "document_type": doc_type,
                "content_type": "application/pdf",
                "policy_id": policy["id"],
            }
            response = client.post("/api/documents/presign", json=presign_request)
            assert response.status_code == 200, f"Failed for {doc_type}"

    def test_claim_document_types(self, client):
        """Should support claim document types (FR-4.3.2)."""
        policyholder = create_test_policyholder(client)
        policy = create_test_policy(client, policyholder["id"])
        claim = create_test_claim(client, policy["id"])

        claim_doc_types = ["PHOTO", "POLICE_REPORT", "INVOICE", "MEDICAL_RECORD"]

        for doc_type in claim_doc_types:
            presign_request = {
                "file_name": f"{doc_type.lower()}.pdf",
                "document_type": doc_type,
                "content_type": "application/pdf",
                "claim_id": claim["id"],
            }
            response = client.post("/api/documents/presign", json=presign_request)
            assert response.status_code == 200, f"Failed for {doc_type}"


class TestDocumentSecurity:
    """Test suite for document security (FR-4 NFR-4)."""

    def test_document_access_audit(self, client):
        """Document access should be auditable (FR-4.2.4)."""
        policyholder = create_test_policyholder(client)
        policy = create_test_policy(client, policyholder["id"])

        presign_request = {
            "file_name": "audit_test.pdf",
            "document_type": "TEST",
            "content_type": "application/pdf",
            "policy_id": policy["id"],
        }
        presign_response = client.post("/api/documents/presign", json=presign_request)
        file_key = presign_response.json()["file_key"]

        register_request = {
            "file_key": file_key,
            "file_name": "audit_test.pdf",
            "document_type": "TEST",
            "policy_id": policy["id"],
        }
        register_response = client.post("/api/documents", json=register_request)
        document_id = register_response.json()["id"]

        # Access document - this should be logged/auditable
        response = client.get(f"/api/documents/{document_id}")
        assert response.status_code == 200
        # Note: Actual audit logging would be in backend logs/CloudWatch

    def test_presigned_url_security(self, client):
        """Presigned URLs should be unique and secure."""
        policyholder = create_test_policyholder(client)
        policy = create_test_policy(client, policyholder["id"])

        presign_request = {
            "file_name": "secure_test.pdf",
            "document_type": "TEST",
            "content_type": "application/pdf",
            "policy_id": policy["id"],
        }

        # Generate two presigned URLs
        response1 = client.post("/api/documents/presign", json=presign_request)
        response2 = client.post("/api/documents/presign", json=presign_request)

        url1 = response1.json()["upload_url"]
        url2 = response2.json()["upload_url"]

        # URLs should contain security signatures
        assert "Signature" in url1 or "X-Amz-Signature" in url1
        assert "Signature" in url2 or "X-Amz-Signature" in url2


class TestDocumentUploadWorkflow:
    """Test suite for complete document upload workflow."""

    def test_complete_upload_workflow(self, client):
        """Test complete workflow: presign → upload (simulated) → register → retrieve."""
        policyholder = create_test_policyholder(client)
        policy = create_test_policy(client, policyholder["id"])
        claim = create_test_claim(client, policy["id"])

        # Step 1: Get presigned upload URL
        presign_request = {
            "file_name": "workflow_test.jpg",
            "document_type": "PHOTO",
            "content_type": "image/jpeg",
            "claim_id": claim["id"],
        }
        presign_response = client.post("/api/documents/presign", json=presign_request)
        assert presign_response.status_code == 200
        file_key = presign_response.json()["file_key"]

        # Step 2: Upload to S3 (simulated - would use presigned URL in real scenario)
        # In real workflow, client would PUT file to presigned URL

        # Step 3: Register document
        register_request = {
            "file_key": file_key,
            "file_name": "workflow_test.jpg",
            "document_type": "PHOTO",
            "claim_id": claim["id"],
        }
        register_response = client.post("/api/documents", json=register_request)
        assert register_response.status_code == 201
        document_id = register_response.json()["id"]

        # Step 4: Retrieve download URL
        download_response = client.get(f"/api/documents/{document_id}")
        assert download_response.status_code == 200
        assert "download_url" in download_response.json()
