"""
Functional tests for Quote Calculator (FR-3).
Generated by TestKraft - AI-powered test generation platform.

User Story:
- As a customer, I want to get instant insurance quotes
- As an agent, I want to generate quotes quickly during customer calls
- Acceptance criteria: Generate quotes in < 2 seconds, accurate calculations, support all product lines
"""
import pytest
from decimal import Decimal


class TestAutoQuotes:
    """Test suite for auto insurance quotes (FR-3.1)."""

    def test_auto_quote_success(self, client, sample_auto_quote_data):
        """Should generate auto insurance quote successfully."""
        response = client.post("/api/quotes/auto", json=sample_auto_quote_data)
        assert response.status_code == 200

        data = response.json()
        assert "premium_monthly" in data
        assert "premium_annual" in data
        assert "coverage_details" in data

        # Verify amounts are numeric
        monthly = Decimal(data["premium_monthly"])
        annual = Decimal(data["premium_annual"])
        assert monthly > 0
        assert annual > 0

    def test_auto_quote_monthly_annual_relationship(self, client, sample_auto_quote_data):
        """Annual premium should be approximately 12x monthly premium."""
        response = client.post("/api/quotes/auto", json=sample_auto_quote_data)
        data = response.json()

        monthly = Decimal(data["premium_monthly"])
        annual = Decimal(data["premium_annual"])

        # Annual should be close to monthly * 12 (within rounding tolerance)
        expected_annual = monthly * 12
        tolerance = Decimal("1.00")  # Allow $1 tolerance for rounding
        assert abs(annual - expected_annual) <= tolerance

    def test_auto_quote_young_driver_higher_premium(self, client):
        """Young drivers (< 25) should have higher premiums (FR-3 business logic)."""
        young_driver = {
            "driver_age": 22,
            "vehicle_year": 2020,
            "coverage_type": "COMPREHENSIVE",
            "annual_mileage": 12000,
        }
        mature_driver = {
            "driver_age": 40,
            "vehicle_year": 2020,
            "coverage_type": "COMPREHENSIVE",
            "annual_mileage": 12000,
        }

        response_young = client.post("/api/quotes/auto", json=young_driver)
        response_mature = client.post("/api/quotes/auto", json=mature_driver)

        assert response_young.status_code == 200
        assert response_mature.status_code == 200

        young_premium = Decimal(response_young.json()["premium_annual"])
        mature_premium = Decimal(response_mature.json()["premium_annual"])

        assert young_premium > mature_premium, "Young driver should have higher premium"

    def test_auto_quote_coverage_type_affects_premium(self, client):
        """Comprehensive coverage should be more expensive than liability."""
        base_data = {
            "driver_age": 30,
            "vehicle_year": 2020,
            "annual_mileage": 12000,
        }

        liability = {**base_data, "coverage_type": "LIABILITY"}
        comprehensive = {**base_data, "coverage_type": "COMPREHENSIVE"}

        response_liability = client.post("/api/quotes/auto", json=liability)
        response_comprehensive = client.post("/api/quotes/auto", json=comprehensive)

        assert response_liability.status_code == 200
        assert response_comprehensive.status_code == 200

        liability_premium = Decimal(response_liability.json()["premium_annual"])
        comprehensive_premium = Decimal(response_comprehensive.json()["premium_annual"])

        assert comprehensive_premium > liability_premium

    def test_auto_quote_validation_age_range(self, client):
        """Should validate driver age is within valid range (16-100)."""
        invalid_young = {
            "driver_age": 15,  # Too young
            "vehicle_year": 2020,
            "coverage_type": "COMPREHENSIVE",
            "annual_mileage": 12000,
        }
        response = client.post("/api/quotes/auto", json=invalid_young)
        assert response.status_code == 422

        invalid_old = {
            "driver_age": 101,  # Too old
            "vehicle_year": 2020,
            "coverage_type": "COMPREHENSIVE",
            "annual_mileage": 12000,
        }
        response = client.post("/api/quotes/auto", json=invalid_old)
        assert response.status_code == 422

    def test_auto_quote_validation_vehicle_year(self, client):
        """Should validate vehicle year is within valid range (1990-2025)."""
        invalid_old = {
            "driver_age": 30,
            "vehicle_year": 1985,  # Too old
            "coverage_type": "COMPREHENSIVE",
            "annual_mileage": 12000,
        }
        response = client.post("/api/quotes/auto", json=invalid_old)
        assert response.status_code == 422

    def test_auto_quote_completes_in_time(self, client, sample_auto_quote_data):
        """Quote generation should complete in < 2 seconds (FR-3 AC)."""
        import time
        start = time.time()
        response = client.post("/api/quotes/auto", json=sample_auto_quote_data)
        duration = time.time() - start

        assert response.status_code == 200
        assert duration < 2.0, f"Quote took {duration:.2f}s, expected < 2s"

    def test_auto_quote_missing_required_fields(self, client):
        """Should reject quote request with missing required fields."""
        incomplete_data = {
            "driver_age": 30,
            # Missing vehicle_year and coverage_type
        }
        response = client.post("/api/quotes/auto", json=incomplete_data)
        assert response.status_code == 422


class TestHomeQuotes:
    """Test suite for home insurance quotes (FR-3.1)."""

    def test_home_quote_success(self, client, sample_home_quote_data):
        """Should generate home insurance quote successfully."""
        response = client.post("/api/quotes/home", json=sample_home_quote_data)
        assert response.status_code == 200

        data = response.json()
        assert "premium_monthly" in data
        assert "premium_annual" in data
        assert "coverage_details" in data

        monthly = Decimal(data["premium_monthly"])
        annual = Decimal(data["premium_annual"])
        assert monthly > 0
        assert annual > 0

    def test_home_quote_monthly_annual_relationship(self, client, sample_home_quote_data):
        """Annual premium should be approximately 12x monthly premium."""
        response = client.post("/api/quotes/home", json=sample_home_quote_data)
        data = response.json()

        monthly = Decimal(data["premium_monthly"])
        annual = Decimal(data["premium_annual"])

        expected_annual = monthly * 12
        tolerance = Decimal("1.00")
        assert abs(annual - expected_annual) <= tolerance

    def test_home_quote_location_risk_affects_premium(self, client):
        """High-risk location should have higher premium than low-risk."""
        base_data = {
            "home_value": "300000.00",
            "home_age_years": 10,
            "coverage_type": "STANDARD",
        }

        low_risk = {**base_data, "location_risk": "LOW"}
        high_risk = {**base_data, "location_risk": "HIGH"}

        response_low = client.post("/api/quotes/home", json=low_risk)
        response_high = client.post("/api/quotes/home", json=high_risk)

        assert response_low.status_code == 200
        assert response_high.status_code == 200

        low_premium = Decimal(response_low.json()["premium_annual"])
        high_premium = Decimal(response_high.json()["premium_annual"])

        assert high_premium > low_premium

    def test_home_quote_value_affects_premium(self, client):
        """Higher home value should result in higher premium."""
        lower_value = {
            "home_value": "200000.00",
            "location_risk": "MEDIUM",
            "home_age_years": 10,
            "coverage_type": "STANDARD",
        }
        higher_value = {
            "home_value": "500000.00",
            "location_risk": "MEDIUM",
            "home_age_years": 10,
            "coverage_type": "STANDARD",
        }

        response_lower = client.post("/api/quotes/home", json=lower_value)
        response_higher = client.post("/api/quotes/home", json=higher_value)

        assert response_lower.status_code == 200
        assert response_higher.status_code == 200

        lower_premium = Decimal(response_lower.json()["premium_annual"])
        higher_premium = Decimal(response_higher.json()["premium_annual"])

        assert higher_premium > lower_premium

    def test_home_quote_coverage_type_affects_premium(self, client):
        """Premium coverage should be more expensive than basic."""
        base_data = {
            "home_value": "300000.00",
            "location_risk": "MEDIUM",
            "home_age_years": 10,
        }

        basic = {**base_data, "coverage_type": "BASIC"}
        premium = {**base_data, "coverage_type": "PREMIUM"}

        response_basic = client.post("/api/quotes/home", json=basic)
        response_premium = client.post("/api/quotes/home", json=premium)

        assert response_basic.status_code == 200
        assert response_premium.status_code == 200

        basic_cost = Decimal(response_basic.json()["premium_annual"])
        premium_cost = Decimal(response_premium.json()["premium_annual"])

        assert premium_cost > basic_cost

    def test_home_quote_validation_home_value(self, client):
        """Should validate home value is within valid range (50k-5M)."""
        invalid_low = {
            "home_value": "25000.00",  # Too low
            "location_risk": "MEDIUM",
            "home_age_years": 10,
            "coverage_type": "STANDARD",
        }
        response = client.post("/api/quotes/home", json=invalid_low)
        assert response.status_code == 422

    def test_home_quote_completes_in_time(self, client, sample_home_quote_data):
        """Quote generation should complete in < 2 seconds."""
        import time
        start = time.time()
        response = client.post("/api/quotes/home", json=sample_home_quote_data)
        duration = time.time() - start

        assert response.status_code == 200
        assert duration < 2.0


class TestLifeQuotes:
    """Test suite for life insurance quotes (FR-3.1)."""

    def test_life_quote_success(self, client, sample_life_quote_data):
        """Should generate life insurance quote successfully."""
        response = client.post("/api/quotes/life", json=sample_life_quote_data)
        assert response.status_code == 200

        data = response.json()
        assert "premium_monthly" in data
        assert "premium_annual" in data
        assert "coverage_details" in data

        monthly = Decimal(data["premium_monthly"])
        annual = Decimal(data["premium_annual"])
        assert monthly > 0
        assert annual > 0

    def test_life_quote_age_affects_premium(self, client):
        """Older applicants should have higher premiums."""
        base_data = {
            "health_score": 80,
            "coverage_amount": "500000.00",
            "term_years": 20,
        }

        younger = {**base_data, "age": 25}
        older = {**base_data, "age": 60}

        response_younger = client.post("/api/quotes/life", json=younger)
        response_older = client.post("/api/quotes/life", json=older)

        assert response_younger.status_code == 200
        assert response_older.status_code == 200

        younger_premium = Decimal(response_younger.json()["premium_annual"])
        older_premium = Decimal(response_older.json()["premium_annual"])

        assert older_premium > younger_premium

    def test_life_quote_health_score_affects_premium(self, client):
        """Better health score should result in lower premium."""
        base_data = {
            "age": 40,
            "coverage_amount": "500000.00",
            "term_years": 20,
        }

        poor_health = {**base_data, "health_score": 40}
        excellent_health = {**base_data, "health_score": 95}

        response_poor = client.post("/api/quotes/life", json=poor_health)
        response_excellent = client.post("/api/quotes/life", json=excellent_health)

        assert response_poor.status_code == 200
        assert response_excellent.status_code == 200

        poor_premium = Decimal(response_poor.json()["premium_annual"])
        excellent_premium = Decimal(response_excellent.json()["premium_annual"])

        assert excellent_premium < poor_premium

    def test_life_quote_coverage_amount_affects_premium(self, client):
        """Higher coverage amount should result in higher premium."""
        base_data = {
            "age": 35,
            "health_score": 80,
            "term_years": 20,
        }

        lower_coverage = {**base_data, "coverage_amount": "250000.00"}
        higher_coverage = {**base_data, "coverage_amount": "1000000.00"}

        response_lower = client.post("/api/quotes/life", json=lower_coverage)
        response_higher = client.post("/api/quotes/life", json=higher_coverage)

        assert response_lower.status_code == 200
        assert response_higher.status_code == 200

        lower_premium = Decimal(response_lower.json()["premium_annual"])
        higher_premium = Decimal(response_higher.json()["premium_annual"])

        assert higher_premium > lower_premium

    def test_life_quote_validation_age_range(self, client):
        """Should validate age is within valid range (18-80)."""
        invalid_young = {
            "age": 16,  # Too young
            "health_score": 80,
            "coverage_amount": "500000.00",
            "term_years": 20,
        }
        response = client.post("/api/quotes/life", json=invalid_young)
        assert response.status_code == 422

        invalid_old = {
            "age": 85,  # Too old
            "health_score": 80,
            "coverage_amount": "500000.00",
            "term_years": 20,
        }
        response = client.post("/api/quotes/life", json=invalid_old)
        assert response.status_code == 422

    def test_life_quote_validation_health_score(self, client):
        """Should validate health score is within valid range (1-100)."""
        invalid_score = {
            "age": 35,
            "health_score": 150,  # Invalid
            "coverage_amount": "500000.00",
            "term_years": 20,
        }
        response = client.post("/api/quotes/life", json=invalid_score)
        assert response.status_code == 422

    def test_life_quote_completes_in_time(self, client, sample_life_quote_data):
        """Quote generation should complete in < 2 seconds."""
        import time
        start = time.time()
        response = client.post("/api/quotes/life", json=sample_life_quote_data)
        duration = time.time() - start

        assert response.status_code == 200
        assert duration < 2.0


class TestQuoteCalculationAccuracy:
    """Test suite for quote calculation accuracy (FR-3.1.8)."""

    def test_quote_amounts_properly_rounded(self, client):
        """All quote amounts should be rounded to 2 decimal places."""
        quote_data = {
            "driver_age": 30,
            "vehicle_year": 2020,
            "coverage_type": "COMPREHENSIVE",
            "annual_mileage": 12000,
        }
        response = client.post("/api/quotes/auto", json=quote_data)
        data = response.json()

        # Check decimal places
        monthly = data["premium_monthly"]
        annual = data["premium_annual"]

        assert len(monthly.split('.')[-1]) <= 2, "Monthly premium should have max 2 decimal places"
        assert len(annual.split('.')[-1]) <= 2, "Annual premium should have max 2 decimal places"

    def test_quote_consistency(self, client):
        """Same input should always produce same quote (deterministic)."""
        quote_data = {
            "driver_age": 30,
            "vehicle_year": 2020,
            "coverage_type": "COMPREHENSIVE",
            "annual_mileage": 12000,
        }

        response1 = client.post("/api/quotes/auto", json=quote_data)
        response2 = client.post("/api/quotes/auto", json=quote_data)

        assert response1.json() == response2.json(), "Quotes should be consistent"
