"""
Functional tests for health check endpoint.
Generated by TestKraft - AI-powered test generation platform.
"""
import pytest


@pytest.mark.asyncio
class TestHealthCheck:
    """Test health check endpoint."""

    async def test_health_check_returns_200(self, client):
        """Health check should return 200 OK."""
        response = await client.get("/health")

        assert response.status_code == 200
        data = response.json()
        assert data["status"] == "healthy"
        assert "service" in data
        assert "version" in data

    async def test_health_check_service_name(self, client):
        """Health check should return correct service name."""
        response = await client.get("/health")

        assert response.status_code == 200
        data = response.json()
        assert "InsureCo" in data["service"]

    async def test_health_check_version(self, client):
        """Health check should return version information."""
        response = await client.get("/health")

        assert response.status_code == 200
        data = response.json()
        assert data["version"] == "1.0.0"
