"""
Functional tests for Policyholder Management (FR-6).
Generated by TestKraft - AI-powered test generation platform.

User Story:
- As an insurance agent, I want to manage policyholder information
- Acceptance criteria: Create, read, update, delete policyholders with validation
"""
import uuid

import pytest


class TestPolicyholderCreation:
    """Test suite for creating policyholders (FR-6.1)."""

    def test_create_policyholder_success(self, client, sample_policyholder_data):
        """Should successfully create a policyholder with valid data."""
        response = client.post("/api/policyholders", json=sample_policyholder_data)

        assert response.status_code == 201
        data = response.json()

        assert "id" in data
        assert uuid.UUID(data["id"])  # Valid UUID
        assert data["first_name"] == sample_policyholder_data["first_name"]
        assert data["last_name"] == sample_policyholder_data["last_name"]
        assert data["email"] == sample_policyholder_data["email"]
        assert data["phone"] == sample_policyholder_data["phone"]
        assert data["address"] == sample_policyholder_data["address"]

    def test_create_policyholder_duplicate_email(self, client, sample_policyholder_data):
        """Should reject duplicate email addresses (409 Conflict)."""
        # Create first policyholder
        response1 = client.post("/api/policyholders", json=sample_policyholder_data)
        assert response1.status_code == 201

        # Attempt to create second with same email
        response2 = client.post("/api/policyholders", json=sample_policyholder_data)
        assert response2.status_code == 409
        assert "already registered" in response2.json()["detail"].lower()

    def test_create_policyholder_missing_required_fields(self, client):
        """Should reject request with missing required fields (422)."""
        incomplete_data = {
            "first_name": "John",
            # Missing last_name and email
        }
        response = client.post("/api/policyholders", json=incomplete_data)
        assert response.status_code == 422

    def test_create_policyholder_minimal_data(self, client):
        """Should create policyholder with only required fields."""
        minimal_data = {
            "first_name": "Jane",
            "last_name": "Smith",
            "email": f"jane.smith.{uuid.uuid4().hex[:8]}@example.com",
        }
        response = client.post("/api/policyholders", json=minimal_data)
        assert response.status_code == 201

        data = response.json()
        assert data["first_name"] == "Jane"
        assert data["last_name"] == "Smith"
        assert data["phone"] is None
        assert data["address"] is None

    def test_create_policyholder_completes_in_time(self, client, sample_policyholder_data):
        """Policyholder creation should complete in < 2 seconds (NFR-1)."""
        import time
        start = time.time()
        response = client.post("/api/policyholders", json=sample_policyholder_data)
        duration = time.time() - start

        assert response.status_code == 201
        assert duration < 2.0, f"Creation took {duration:.2f}s, expected < 2s"


class TestPolicyholderRetrieval:
    """Test suite for retrieving policyholders (FR-6.2)."""

    def test_list_policyholders_success(self, client):
        """Should list all policyholders with pagination."""
        # Create test policyholders
        for i in range(3):
            data = {
                "first_name": f"User{i}",
                "last_name": f"Test{i}",
                "email": f"user{i}.{uuid.uuid4().hex[:6]}@example.com",
            }
            client.post("/api/policyholders", json=data)

        response = client.get("/api/policyholders")
        assert response.status_code == 200

        data = response.json()
        assert isinstance(data, list)
        assert len(data) >= 3

    def test_list_policyholders_pagination(self, client):
        """Should support pagination with skip and limit."""
        # Create test data
        for i in range(5):
            data = {
                "first_name": f"Page{i}",
                "last_name": "Test",
                "email": f"page{i}.{uuid.uuid4().hex[:6]}@example.com",
            }
            client.post("/api/policyholders", json=data)

        # Test pagination
        response = client.get("/api/policyholders?skip=0&limit=2")
        assert response.status_code == 200
        assert len(response.json()) <= 2

    def test_get_policyholder_by_id_success(self, client, sample_policyholder_data):
        """Should retrieve policyholder by ID."""
        # Create policyholder
        create_response = client.post("/api/policyholders", json=sample_policyholder_data)
        policyholder_id = create_response.json()["id"]

        # Retrieve by ID
        response = client.get(f"/api/policyholders/{policyholder_id}")
        assert response.status_code == 200

        data = response.json()
        assert data["id"] == policyholder_id
        assert data["email"] == sample_policyholder_data["email"]

    def test_get_policyholder_not_found(self, client):
        """Should return 404 for non-existent policyholder."""
        fake_id = uuid.uuid4()
        response = client.get(f"/api/policyholders/{fake_id}")
        assert response.status_code == 404
        assert "not found" in response.json()["detail"].lower()

    def test_get_policyholder_invalid_uuid(self, client):
        """Should return 422 for invalid UUID format."""
        response = client.get("/api/policyholders/invalid-uuid")
        assert response.status_code == 422


class TestPolicyholderUpdate:
    """Test suite for updating policyholders (FR-6.3)."""

    def test_update_policyholder_success(self, client, sample_policyholder_data):
        """Should successfully update policyholder details."""
        # Create policyholder
        create_response = client.post("/api/policyholders", json=sample_policyholder_data)
        policyholder_id = create_response.json()["id"]

        # Update details
        update_data = {
            "phone": "+1-555-9999",
            "address": "789 New Address St, New City, NC 54321",
        }
        response = client.put(f"/api/policyholders/{policyholder_id}", json=update_data)
        assert response.status_code == 200

        data = response.json()
        assert data["phone"] == "+1-555-9999"
        assert data["address"] == "789 New Address St, New City, NC 54321"
        # Email should remain unchanged
        assert data["email"] == sample_policyholder_data["email"]

    def test_update_policyholder_partial_update(self, client, sample_policyholder_data):
        """Should support partial updates (only specified fields)."""
        # Create policyholder
        create_response = client.post("/api/policyholders", json=sample_policyholder_data)
        policyholder_id = create_response.json()["id"]

        # Update only first name
        update_data = {"first_name": "UpdatedName"}
        response = client.put(f"/api/policyholders/{policyholder_id}", json=update_data)
        assert response.status_code == 200

        data = response.json()
        assert data["first_name"] == "UpdatedName"
        assert data["last_name"] == sample_policyholder_data["last_name"]

    def test_update_policyholder_not_found(self, client):
        """Should return 404 when updating non-existent policyholder."""
        fake_id = uuid.uuid4()
        update_data = {"phone": "+1-555-0000"}
        response = client.put(f"/api/policyholders/{fake_id}", json=update_data)
        assert response.status_code == 404


class TestPolicyholderDeletion:
    """Test suite for deleting policyholders (FR-6.4)."""

    def test_delete_policyholder_success(self, client, sample_policyholder_data):
        """Should successfully delete (soft-delete) a policyholder."""
        # Create policyholder
        create_response = client.post("/api/policyholders", json=sample_policyholder_data)
        policyholder_id = create_response.json()["id"]

        # Delete policyholder
        response = client.delete(f"/api/policyholders/{policyholder_id}")
        assert response.status_code == 204

    def test_delete_policyholder_not_found(self, client):
        """Should return 404 when deleting non-existent policyholder."""
        fake_id = uuid.uuid4()
        response = client.delete(f"/api/policyholders/{fake_id}")
        assert response.status_code == 404

    def test_deleted_policyholder_not_retrievable(self, client, sample_policyholder_data):
        """Deleted policyholder should not be retrievable."""
        # Create and delete policyholder
        create_response = client.post("/api/policyholders", json=sample_policyholder_data)
        policyholder_id = create_response.json()["id"]
        client.delete(f"/api/policyholders/{policyholder_id}")

        # Attempt to retrieve
        response = client.get(f"/api/policyholders/{policyholder_id}")
        assert response.status_code == 404


class TestPolicyholderValidation:
    """Test suite for policyholder data validation."""

    def test_email_validation(self, client):
        """Should validate email format."""
        invalid_data = {
            "first_name": "Test",
            "last_name": "User",
            "email": "not-an-email",  # Invalid format
        }
        response = client.post("/api/policyholders", json=invalid_data)
        # May be 422 (validation error) or accepted depending on validation rules
        # Testing that system handles it gracefully
        assert response.status_code in [201, 422]

    def test_phone_format_accepted(self, client):
        """Should accept various phone formats."""
        data = {
            "first_name": "Test",
            "last_name": "User",
            "email": f"test.{uuid.uuid4().hex[:8]}@example.com",
            "phone": "(555) 123-4567",
        }
        response = client.post("/api/policyholders", json=data)
        assert response.status_code == 201
