"""
Functional tests for Claims Processing (FR-2).
Generated by TestKraft - AI-powered test generation platform.

User Story:
- As a policyholder, I want to file claims and track their status
- As a claims adjuster, I want to review and approve/deny claims with fraud detection
- Acceptance criteria: File claims, validate against policy, track status, fraud detection
"""
import uuid
from datetime import date, timedelta

import pytest

from conftest import create_test_policyholder, create_test_policy


class TestClaimFiling:
    """Test suite for filing claims (FR-2.1)."""

    def test_file_claim_success(self, client, sample_claim_data):
        """Should successfully file a claim against an active policy."""
        # Create policyholder and policy
        policyholder = create_test_policyholder(client)
        policy = create_test_policy(client, policyholder["id"])

        # File claim
        sample_claim_data["policy_id"] = policy["id"]
        response = client.post("/api/claims", json=sample_claim_data)

        assert response.status_code == 201
        data = response.json()

        assert "id" in data
        assert uuid.UUID(data["id"])
        assert data["policy_id"] == policy["id"]
        assert data["claim_type"] == sample_claim_data["claim_type"]
        assert data["description"] == sample_claim_data["description"]
        assert data["amount_requested"] == sample_claim_data["amount_requested"]
        assert data["status"] == "SUBMITTED"

    def test_file_claim_auto_generates_claim_number(self, client):
        """Claim should auto-generate unique claim number (FR-2.1.2)."""
        policyholder = create_test_policyholder(client)
        policy = create_test_policy(client, policyholder["id"])

        claim_data = {
            "policy_id": policy["id"],
            "claim_type": "COLLISION",
            "description": "Vehicle accident on highway",
            "amount_requested": "5000.00",
            "incident_date": (date.today() - timedelta(days=3)).isoformat(),
        }

        response = client.post("/api/claims", json=claim_data)
        assert response.status_code == 201

        data = response.json()
        assert "claim_number" in data
        assert data["claim_number"].startswith("CLM-")
        assert len(data["claim_number"]) > 4

    def test_file_claim_validates_policy_exists(self, client, sample_claim_data):
        """Should reject claim for non-existent policy (FR-2.1.6)."""
        sample_claim_data["policy_id"] = str(uuid.uuid4())
        response = client.post("/api/claims", json=sample_claim_data)
        assert response.status_code == 404
        assert "policy" in response.json()["detail"].lower()

    def test_file_claim_validates_amount_within_coverage(self, client):
        """Should reject claim if amount exceeds coverage (FR-2.1.7)."""
        policyholder = create_test_policyholder(client)
        policy_data = {
            "policy_type": "AUTO",
            "premium_amount": "1000.00",
            "coverage_amount": "10000.00",  # Low coverage
            "start_date": date.today().isoformat(),
            "end_date": (date.today() + timedelta(days=365)).isoformat(),
            "status": "ACTIVE",
        }
        policy = create_test_policy(client, policyholder["id"], policy_data)

        # Claim exceeds coverage
        claim_data = {
            "policy_id": policy["id"],
            "claim_type": "THEFT",
            "description": "Vehicle stolen from parking lot",
            "amount_requested": "50000.00",  # Exceeds coverage
            "incident_date": date.today().isoformat(),
        }

        response = client.post("/api/claims", json=claim_data)
        assert response.status_code == 422
        assert "coverage" in response.json()["detail"].lower()

    def test_file_claim_validates_policy_active(self, client):
        """Should reject claim if policy is not ACTIVE (FR-2.1.6)."""
        policyholder = create_test_policyholder(client)
        policy_data = {
            "policy_type": "AUTO",
            "premium_amount": "1000.00",
            "coverage_amount": "50000.00",
            "start_date": date.today().isoformat(),
            "end_date": (date.today() + timedelta(days=365)).isoformat(),
            "status": "CANCELLED",  # Not active
        }
        policy = create_test_policy(client, policyholder["id"], policy_data)

        claim_data = {
            "policy_id": policy["id"],
            "claim_type": "COLLISION",
            "description": "Test claim",
            "amount_requested": "3000.00",
            "incident_date": date.today().isoformat(),
        }

        response = client.post("/api/claims", json=claim_data)
        assert response.status_code == 422

    def test_file_claim_missing_required_fields(self, client):
        """Should reject claim with missing required fields."""
        incomplete_data = {
            "claim_type": "COLLISION",
            # Missing policy_id, description, amount_requested, incident_date
        }
        response = client.post("/api/claims", json=incomplete_data)
        assert response.status_code == 422

    def test_file_claim_description_max_length(self, client):
        """Should validate description length (500 char max per FR-2.1.4)."""
        policyholder = create_test_policyholder(client)
        policy = create_test_policy(client, policyholder["id"])

        claim_data = {
            "policy_id": policy["id"],
            "claim_type": "COLLISION",
            "description": "A" * 600,  # Exceeds 500 chars
            "amount_requested": "3000.00",
            "incident_date": date.today().isoformat(),
        }

        response = client.post("/api/claims", json=claim_data)
        # May be accepted or rejected depending on validation
        assert response.status_code in [201, 422]

    def test_file_claim_completes_in_time(self, client):
        """Claim filing should complete in < 5 seconds (FR-2 AC)."""
        import time
        policyholder = create_test_policyholder(client)
        policy = create_test_policy(client, policyholder["id"])

        claim_data = {
            "policy_id": policy["id"],
            "claim_type": "COLLISION",
            "description": "Performance test claim",
            "amount_requested": "5000.00",
            "incident_date": date.today().isoformat(),
        }

        start = time.time()
        response = client.post("/api/claims", json=claim_data)
        duration = time.time() - start

        assert response.status_code == 201
        assert duration < 5.0, f"Claim filing took {duration:.2f}s, expected < 5s"


class TestClaimRetrieval:
    """Test suite for retrieving claims (FR-2.4)."""

    def test_list_claims_success(self, client):
        """Should list all claims with pagination."""
        policyholder = create_test_policyholder(client)
        policy = create_test_policy(client, policyholder["id"])

        # Create multiple claims
        for i in range(3):
            claim_data = {
                "policy_id": policy["id"],
                "claim_type": "COLLISION",
                "description": f"Test claim {i}",
                "amount_requested": f"{1000 + i * 500}.00",
                "incident_date": (date.today() - timedelta(days=i)).isoformat(),
            }
            client.post("/api/claims", json=claim_data)

        response = client.get("/api/claims")
        assert response.status_code == 200
        assert isinstance(response.json(), list)
        assert len(response.json()) >= 3

    def test_list_claims_filter_by_status(self, client):
        """Should filter claims by status (FR-2.2.2)."""
        policyholder = create_test_policyholder(client)
        policy = create_test_policy(client, policyholder["id"])

        # Create claim
        claim_data = {
            "policy_id": policy["id"],
            "claim_type": "THEFT",
            "description": "Stolen property",
            "amount_requested": "2000.00",
            "incident_date": date.today().isoformat(),
        }
        response = client.post("/api/claims", json=claim_data)
        claim_id = response.json()["id"]

        # Filter by status
        response = client.get("/api/claims?status=SUBMITTED")
        assert response.status_code == 200
        claims = response.json()
        if claims:
            assert all(c["status"] == "SUBMITTED" for c in claims)

    def test_list_claims_filter_by_policy(self, client):
        """Should filter claims by policy_id."""
        policyholder = create_test_policyholder(client)
        policy1 = create_test_policy(client, policyholder["id"])
        policy2 = create_test_policy(client, policyholder["id"])

        # Create claim for policy1
        claim_data = {
            "policy_id": policy1["id"],
            "claim_type": "COLLISION",
            "description": "Test claim for policy 1",
            "amount_requested": "3000.00",
            "incident_date": date.today().isoformat(),
        }
        client.post("/api/claims", json=claim_data)

        # Filter by policy
        response = client.get(f"/api/claims?policy_id={policy1['id']}")
        assert response.status_code == 200
        claims = response.json()
        if claims:
            assert all(c["policy_id"] == policy1["id"] for c in claims)

    def test_get_claim_by_id_success(self, client):
        """Should retrieve claim by ID with details (FR-2.2.3)."""
        policyholder = create_test_policyholder(client)
        policy = create_test_policy(client, policyholder["id"])

        claim_data = {
            "policy_id": policy["id"],
            "claim_type": "FIRE",
            "description": "Fire damage to property",
            "amount_requested": "15000.00",
            "incident_date": date.today().isoformat(),
        }
        create_response = client.post("/api/claims", json=claim_data)
        claim_id = create_response.json()["id"]

        # Retrieve by ID
        response = client.get(f"/api/claims/{claim_id}")
        assert response.status_code == 200

        data = response.json()
        assert data["id"] == claim_id
        assert data["claim_type"] == "FIRE"

    def test_get_claim_not_found(self, client):
        """Should return 404 for non-existent claim."""
        fake_id = uuid.uuid4()
        response = client.get(f"/api/claims/{fake_id}")
        assert response.status_code == 404
        assert "not found" in response.json()["detail"].lower()


class TestClaimUpdate:
    """Test suite for updating claims (FR-2.2)."""

    def test_update_claim_details(self, client):
        """Should update claim details."""
        policyholder = create_test_policyholder(client)
        policy = create_test_policy(client, policyholder["id"])

        claim_data = {
            "policy_id": policy["id"],
            "claim_type": "COLLISION",
            "description": "Original description",
            "amount_requested": "3000.00",
            "incident_date": date.today().isoformat(),
        }
        create_response = client.post("/api/claims", json=claim_data)
        claim_id = create_response.json()["id"]

        # Update description
        update_data = {"description": "Updated description with more details"}
        response = client.put(f"/api/claims/{claim_id}", json=update_data)
        assert response.status_code == 200
        assert response.json()["description"] == "Updated description with more details"

    def test_update_claim_not_found(self, client):
        """Should return 404 when updating non-existent claim."""
        fake_id = uuid.uuid4()
        update_data = {"description": "Updated"}
        response = client.put(f"/api/claims/{fake_id}", json=update_data)
        assert response.status_code == 404


class TestClaimApproval:
    """Test suite for approving claims (FR-2.2.6)."""

    def test_approve_claim_success(self, client):
        """Should successfully approve a claim (FR-2.2.6)."""
        policyholder = create_test_policyholder(client)
        policy = create_test_policy(client, policyholder["id"])

        claim_data = {
            "policy_id": policy["id"],
            "claim_type": "COLLISION",
            "description": "Approved claim test",
            "amount_requested": "5000.00",
            "incident_date": date.today().isoformat(),
        }
        create_response = client.post("/api/claims", json=claim_data)
        claim_id = create_response.json()["id"]

        # Approve claim
        approval_data = {
            "amount_approved": "4500.00",
            "notes": "Approved after review",
        }
        response = client.post(f"/api/claims/{claim_id}/approve", json=approval_data)
        assert response.status_code == 200

        data = response.json()
        assert data["status"] == "APPROVED"
        assert data["amount_approved"] == "4500.00"

    def test_approve_claim_different_amount(self, client):
        """Approved amount can differ from requested amount (FR-2.2.6)."""
        policyholder = create_test_policyholder(client)
        policy = create_test_policy(client, policyholder["id"])

        claim_data = {
            "policy_id": policy["id"],
            "claim_type": "THEFT",
            "description": "Partial approval test",
            "amount_requested": "10000.00",
            "incident_date": date.today().isoformat(),
        }
        create_response = client.post("/api/claims", json=claim_data)
        claim_id = create_response.json()["id"]

        # Approve with lower amount
        approval_data = {"amount_approved": "7000.00"}
        response = client.post(f"/api/claims/{claim_id}/approve", json=approval_data)
        assert response.status_code == 200
        assert response.json()["amount_approved"] == "7000.00"

    def test_approve_claim_invalid_status(self, client):
        """Should reject approval if claim not in correct status (FR-2.2.6)."""
        policyholder = create_test_policyholder(client)
        policy = create_test_policy(client, policyholder["id"])

        claim_data = {
            "policy_id": policy["id"],
            "claim_type": "COLLISION",
            "description": "Status validation test",
            "amount_requested": "3000.00",
            "incident_date": date.today().isoformat(),
        }
        create_response = client.post("/api/claims", json=claim_data)
        claim_id = create_response.json()["id"]

        # Approve first time
        approval_data = {"amount_approved": "3000.00"}
        response = client.post(f"/api/claims/{claim_id}/approve", json=approval_data)
        assert response.status_code == 200

        # Try to approve again (should fail)
        response = client.post(f"/api/claims/{claim_id}/approve", json=approval_data)
        assert response.status_code == 422

    def test_approve_claim_not_found(self, client):
        """Should return 404 when approving non-existent claim."""
        fake_id = uuid.uuid4()
        approval_data = {"amount_approved": "1000.00"}
        response = client.post(f"/api/claims/{fake_id}/approve", json=approval_data)
        assert response.status_code == 404


class TestClaimRejection:
    """Test suite for rejecting claims (FR-2.2.7)."""

    def test_reject_claim_success(self, client):
        """Should successfully reject a claim (FR-2.2.7)."""
        policyholder = create_test_policyholder(client)
        policy = create_test_policy(client, policyholder["id"])

        claim_data = {
            "policy_id": policy["id"],
            "claim_type": "LIABILITY",
            "description": "Rejection test claim",
            "amount_requested": "2000.00",
            "incident_date": date.today().isoformat(),
        }
        create_response = client.post("/api/claims", json=claim_data)
        claim_id = create_response.json()["id"]

        # Reject claim
        rejection_data = {"reason": "Insufficient evidence provided"}
        response = client.post(f"/api/claims/{claim_id}/reject", json=rejection_data)
        assert response.status_code == 200
        assert response.json()["status"] == "REJECTED"

    def test_reject_claim_invalid_status(self, client):
        """Should reject if claim not in correct status."""
        policyholder = create_test_policyholder(client)
        policy = create_test_policy(client, policyholder["id"])

        claim_data = {
            "policy_id": policy["id"],
            "claim_type": "COLLISION",
            "description": "Status validation test",
            "amount_requested": "3000.00",
            "incident_date": date.today().isoformat(),
        }
        create_response = client.post("/api/claims", json=claim_data)
        claim_id = create_response.json()["id"]

        # Approve first
        client.post(f"/api/claims/{claim_id}/approve", json={"amount_approved": "3000.00"})

        # Try to reject (should fail - already approved)
        rejection_data = {"reason": "Testing"}
        response = client.post(f"/api/claims/{claim_id}/reject", json=rejection_data)
        assert response.status_code == 422

    def test_reject_claim_not_found(self, client):
        """Should return 404 when rejecting non-existent claim."""
        fake_id = uuid.uuid4()
        rejection_data = {"reason": "Not found test"}
        response = client.post(f"/api/claims/{fake_id}/reject", json=rejection_data)
        assert response.status_code == 404


class TestClaimBusinessRules:
    """Test suite for claim business rules and validation."""

    def test_claim_amount_validation(self, client):
        """Claim amount must be within policy coverage."""
        policyholder = create_test_policyholder(client)
        policy_data = {
            "policy_type": "AUTO",
            "premium_amount": "1000.00",
            "coverage_amount": "25000.00",
            "start_date": date.today().isoformat(),
            "end_date": (date.today() + timedelta(days=365)).isoformat(),
            "status": "ACTIVE",
        }
        policy = create_test_policy(client, policyholder["id"], policy_data)

        # Valid claim (within coverage)
        valid_claim = {
            "policy_id": policy["id"],
            "claim_type": "COLLISION",
            "description": "Valid claim within coverage",
            "amount_requested": "20000.00",
            "incident_date": date.today().isoformat(),
        }
        response = client.post("/api/claims", json=valid_claim)
        assert response.status_code == 201

        # Invalid claim (exceeds coverage)
        invalid_claim = {
            "policy_id": policy["id"],
            "claim_type": "COLLISION",
            "description": "Invalid claim exceeds coverage",
            "amount_requested": "30000.00",
            "incident_date": date.today().isoformat(),
        }
        response = client.post("/api/claims", json=invalid_claim)
        assert response.status_code == 422
